export interface BlogArticle {
  id: string;
  title: string;
  slug: string;
  category: "airline" | "airport" | "regulation" | "guide" | "situation";
  wordCount: number;
  readTime: string;
  excerpt: string;
  publishDate: string;
  featured: boolean;
  color?: "blue" | "green" | "purple" | "orange" | "red" | "amber";
}

export const blogArticlesEn: BlogArticle[] = [
  {
    id: "1",
    title: "LOT Polish Airlines Flight Delay Compensation: Complete Guide for International Passengers",
    slug: "lot-polish-airlines-delay-compensation-guide",
    category: "airline",
    wordCount: 3200,
    readTime: "12 min read",
    excerpt: "Comprehensive guide to claiming up to €600 compensation for LOT Polish Airlines delayed flights. Learn your rights under EU261/2004 and how to file a successful claim.",
    publishDate: "2025-03-05",
    featured: true,
    color: "blue",
  },
  {
    id: "2",
    title: "LOT Polish Airlines Cancelled Flight: How to Claim Up to €600 Compensation",
    slug: "lot-polish-airlines-cancelled-flight-compensation",
    category: "airline",
    wordCount: 3100,
    readTime: "11 min read",
    excerpt: "Step-by-step guide to claiming compensation when LOT Polish Airlines cancels your flight. Understand your passenger rights and maximize your claim.",
    publishDate: "2025-03-05",
    featured: true,
    color: "blue",
  },
  {
    id: "3",
    title: "LOT Polish Airlines Denied Boarding Compensation: Your Rights When They Overbook",
    slug: "lot-polish-airlines-denied-boarding-compensation",
    category: "airline",
    wordCount: 2900,
    readTime: "10 min read",
    excerpt: "What to do when LOT Polish Airlines denies you boarding due to overbooking. Learn about your compensation rights and how to claim up to €600.",
    publishDate: "2025-03-05",
    featured: true,
    color: "blue",
  },
  {
    id: "4",
    title: "How Much Compensation Can You Claim from LOT Polish Airlines? €250, €400, or €600",
    slug: "lot-polish-airlines-compensation-amounts",
    category: "guide",
    wordCount: 2700,
    readTime: "9 min read",
    excerpt: "Complete breakdown of LOT Polish Airlines compensation amounts. Understand how distance and delay length determine your €250, €400, or €600 payout.",
    publishDate: "2025-03-05",
    featured: true,
    color: "green",
  },
  {
    id: "5",
    title: "LOT Polish Airlines Rejected My Compensation Claim: What to Do Next",
    slug: "lot-polish-airlines-rejected-compensation-claim",
    category: "guide",
    wordCount: 2800,
    readTime: "10 min read",
    excerpt: "LOT denied your compensation claim? Learn why airlines reject claims, how to appeal, and when to escalate to national enforcement bodies.",
    publishDate: "2025-03-05",
    featured: true,
    color: "orange",
  },
  {
    id: "6",
    title: "LOT Polish Airlines Voucher Instead of Cash: Do You Have to Accept It?",
    slug: "lot-polish-airlines-voucher-vs-cash",
    category: "guide",
    wordCount: 2400,
    readTime: "8 min read",
    excerpt: "LOT offering a voucher instead of cash compensation? Understand your legal right to monetary payment and how to demand what you're owed.",
    publishDate: "2025-03-05",
    featured: false,
    color: "purple",
  },
  {
    id: "7",
    title: "How Long Does LOT Polish Airlines Take to Pay Compensation?",
    slug: "lot-polish-airlines-compensation-payment-timeline",
    category: "guide",
    wordCount: 2600,
    readTime: "9 min read",
    excerpt: "Expected timelines for LOT Polish Airlines compensation payments, what causes delays, and legal steps if they refuse or ignore your claim.",
    publishDate: "2025-03-05",
    featured: false,
    color: "blue",
  },
  {
    id: "8",
    title: "Ryanair Compensation Guide 2025: How to Claim for Delays & Cancellations",
    slug: "ryanair-compensation-guide",
    category: "airline",
    wordCount: 3500,
    readTime: "16 min read",
    excerpt: "Complete guide to claiming Ryanair compensation. Learn how to navigate the claim process for Europe's largest low-cost airline.",
    publishDate: "2025-03-06",
    featured: false,
    color: "blue",
  },
  {
    id: "9",
    title: "Wizz Air Compensation Guide 2025: Flight Delays & Cancellations",
    slug: "wizz-air-compensation-guide",
    category: "airline",
    wordCount: 3500,
    readTime: "16 min read",
    excerpt: "Step-by-step guide to Wizz Air compensation claims. Understand your rights and how to get paid for delays and cancellations.",
    publishDate: "2025-03-06",
    featured: false,
    color: "purple",
  },
  {
    id: "10",
    title: "Lufthansa Compensation Guide 2025: Delays, Cancellations & Strikes",
    slug: "lufthansa-compensation-guide",
    category: "airline",
    wordCount: 3400,
    readTime: "15 min read",
    excerpt: "Comprehensive guide to Lufthansa compensation. How to claim for delays, cancellations, and strikes with the German flag carrier.",
    publishDate: "2025-03-06",
    featured: false,
    color: "blue",
  },
  {
    id: "11",
    title: "EasyJet Compensation Guide 2025: Your Complete Rights Manual",
    slug: "easyjet-compensation-guide",
    category: "airline",
    wordCount: 3300,
    readTime: "15 min read",
    excerpt: "Complete guide to claiming EasyJet compensation. Navigate the claim process for delays and cancellations with expert tips.",
    publishDate: "2025-03-06",
    featured: false,
    color: "orange",
  },
  {
    id: "12",
    title: "British Airways Compensation Guide 2025: Delays & Cancellations",
    slug: "british-airways-compensation-guide",
    category: "airline",
    wordCount: 3600,
    readTime: "17 min read",
    excerpt: "Complete guide to claiming British Airways compensation. Navigate BA's claim process for flight delays and cancellations.",
    publishDate: "2025-03-06",
    featured: false,
    color: "blue",
  },
  {
    id: "13",
    title: "KLM Compensation Guide 2025: Flight Delays & Cancellations",
    slug: "klm-compensation-guide",
    category: "airline",
    wordCount: 3200,
    readTime: "14 min read",
    excerpt: "Complete guide to claiming KLM compensation for delays and cancellations. Navigate the Dutch airline's claim process successfully.",
    publishDate: "2025-03-06",
    featured: false,
    color: "blue",
  },
  {
    id: "14",
    title: "Air France Compensation Guide 2025: Delays & Cancellations",
    slug: "air-france-compensation-guide",
    category: "airline",
    wordCount: 3100,
    readTime: "15 min read",
    excerpt: "Complete guide to claiming Air France compensation. Learn the process, timelines, and how to maximize your claim success.",
    publishDate: "2025-03-06",
    featured: false,
    color: "blue",
  },
  {
    id: "15",
    title: "SWISS Compensation Guide 2025: Flight Delays & Cancellations",
    slug: "swiss-compensation-guide",
    category: "airline",
    wordCount: 3000,
    readTime: "13 min read",
    excerpt: "Complete guide to claiming SWISS compensation for flight delays and cancellations. Navigate the Swiss airline's claim process.",
    publishDate: "2025-03-06",
    featured: false,
    color: "red",
  },
  {
    id: "16",
    title: "How Much Compensation for a Delayed Flight? €250, €400 or €600",
    slug: "how-much-compensation-delayed-flight",
    category: "guide",
    wordCount: 2800,
    readTime: "10 min read",
    excerpt: "Exact EU261 compensation amounts explained: €250 for flights under 1,500 km, €400 for 1,500–3,500 km, €600 for over 3,500 km. See when you qualify and how to claim.",
    publishDate: "2025-03-07",
    featured: true,
    color: "blue",
  },
  {
    id: "17",
    title: "Does EU261 Apply to Non-EU Airlines?",
    slug: "eu261-non-eu-airlines-does-it-apply",
    category: "regulation",
    wordCount: 2600,
    readTime: "9 min read",
    excerpt: "EU261 applies to ALL airlines when flying from an EU airport — including Emirates, Turkish Airlines, and United. Non-EU airlines are NOT covered on flights arriving into the EU.",
    publishDate: "2025-03-07",
    featured: true,
    color: "purple",
  },
  {
    id: "18",
    title: "What Counts as a Flight Delay Under EU261?",
    slug: "what-counts-flight-delay-eu261",
    category: "regulation",
    wordCount: 2700,
    readTime: "10 min read",
    excerpt: "EU261 compensation triggers at 3+ hours arrival delay — not departure delay. Learn exactly how delay is measured, which scenarios qualify, and when extraordinary circumstances apply.",
    publishDate: "2026-03-26",
    featured: true,
    color: "blue",
  },
  {
    id: "19",
    title: "What Are Extraordinary Circumstances Under EU261?",
    slug: "extraordinary-circumstances-eu261-definition",
    category: "regulation",
    wordCount: 2900,
    readTime: "10 min read",
    excerpt: "Extraordinary circumstances exempt airlines from EU261 compensation — but only when proven. Learn what qualifies, what doesn't, and how to challenge a wrongful airline rejection.",
    publishDate: "2026-03-26",
    featured: true,
    color: "purple",
  },
];
