import { BlogArticle } from "@/lib/blogArticles";

export const blogArticlesSv: BlogArticle[] = [
  {
    id: "1",
    title: "Ersättning för försenat SAS-flyg — komplett guide 2025",
    slug: "sas-forsenat-flyg-ersattning",
    excerpt: "Var ditt SAS-flyg försenat? Läs vår kompletta guide om hur du får upp till 600 € i ersättning från SAS. Regler, belopp och steg-för-steg instruktioner.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "8 min",
    category: "SAS",
    color: "blue",
    featured: true
  },
  {
    id: "2",
    title: "SAS ställde in flyget — hur får du upp till 600 € i ersättning?",
    slug: "sas-installt-flyg-ersattning",
    excerpt: "Blev ditt SAS-flyg inställt? Läs om dina rättigheter till ombokning, återbetalning och kompensation upp till 600 €. Guide för drabbade passagerare.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "9 min",
    category: "SAS",
    color: "red",
    featured: true
  },
  {
    id: "3",
    title: "SAS nekade ersättning — vad gör du härnäst?",
    slug: "sas-nekade-ersattning",
    excerpt: "Har SAS nekat din ersättning? Ge inte upp! Många avslag är felaktiga. Läs vår guide om hur du överklagar och vinner mot SAS.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "SAS",
    color: "orange",
    featured: false
  },
  {
    id: "4",
    title: "SAS erbjuder voucher istället för pengar — måste du acceptera det?",
    slug: "sas-voucher-eller-pengar",
    excerpt: "Erbjuder SAS en voucher? Läs varför kontanter nästan alltid är bättre och hur du tackar nej på rätt sätt enligt EU-lag.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "5",
    title: "Hur lång tid tar det för SAS att betala ersättning?",
    slug: "sas-utbetalningstid-ersattning",
    excerpt: "Väntar du på pengar från SAS? Här är den brutala sanningen om väntetider 2025 och tips för att snabba på din utbetalning.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "green",
    featured: false
  },
  {
    id: "6",
    title: "Hur mycket ersättning kan du kräva från SAS? (Tabell)",
    slug: "sas-ersattning-belopp-tabell",
    excerpt: "250 €, 400 € eller 600 €? Se vår enkla tabell baserad på flygsträcka och räkna ut exakt vad SAS är skyldiga dig.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "4 min",
    category: "SAS",
    color: "yellow",
    featured: false
  },
  {
    id: "7",
    title: "Ersättning vs. återbetalning av biljett hos SAS — vad är skillnaden?",
    slug: "sas-ersattning-vs-aterbetalning",
    excerpt: "Blandar du ihop återbetalning med ersättning? Läs om när du kan få båda — pengarna tillbaka för biljetten PLUS upp till 600 € i skadestånd.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "green",
    featured: false
  },
  {
    id: "8",
    title: "SAS försening vs. inställt flyg — olika regler, olika ersättning",
    slug: "sas-forsening-vs-installt-flyg",
    excerpt: "Är ditt flyg försenat eller inställt? Gränsen är hårfin men viktig. Vi förklarar skillnaderna i dina rättigheter och hur du maximerar din ersättning.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "9",
    title: "SAS försenat mer än 3 timmar — dina rättigheter steg för steg",
    slug: "sas-forsenat-mer-an-3-timmar",
    excerpt: "Har ditt SAS-flyg landat mer än 3 timmar för sent? Läs vår guide om hur du säkrar upp till 600 € i ersättning. Steg-för-steg instruktioner.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "blue",
    featured: true
  },
  {
    id: "10",
    title: "SAS ställde in flyget mindre än 14 dagar före avgång — ersättning",
    slug: "sas-installt-flyg-14-dagar",
    excerpt: "14-dagarsregeln är avgörande. Fick du veta om inställningen för sent? Se hur du kräver ersättning från SAS.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "SAS",
    color: "red",
    featured: false
  },
  {
    id: "11",
    title: "SAS ställde in flyget mindre än 7 dagar före avgång — sista minuten",
    slug: "sas-installt-flyg-7-dagar",
    excerpt: "Inställt sista veckan? Kraven på SAS är stenhårda. Se varför du nästan alltid har rätt till ersättning vid sena besked.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "red",
    featured: false
  },
  {
    id: "12",
    title: "SAS försenat mer än 3 timmar — dina rättigheter steg för steg",
    slug: "sas-forsenat-mer-an-3-timmar",
    excerpt: "Har ditt SAS-flyg landat mer än 3 timmar för sent? Läs vår guide om hur du säkrar upp till 600 € i ersättning. Steg-för-steg instruktioner.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "blue",
    featured: true
  },
  {
    id: "13",
    title: "SAS ställde in flyget mindre än 14 dagar före avgång — ersättning",
    slug: "sas-installt-flyg-14-dagar",
    excerpt: "14-dagarsregeln är avgörande. Fick du veta om inställningen för sent? Se hur du kräver ersättning från SAS.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "SAS",
    color: "red",
    featured: false
  },
  {
    id: "14",
    title: "SAS ställde in flyget mindre än 7 dagar före avgång — sista minuten",
    slug: "sas-installt-flyg-7-dagar",
    excerpt: "Inställt sista veckan? Kraven på SAS är stenhårda. Se varför du nästan alltid har rätt till ersättning vid sena besked.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "red",
    featured: false
  },
  {
    id: "16",
    title: "Missat anslutningsflyg på grund av SAS-försening — vem betalar?",
    slug: "sas-missat-anslutningsflyg",
    excerpt: "Missade du ditt nästa flyg p.g.a. SAS? Om du har en genomgående biljett ansvarar SAS för hela resan. Läs om ersättning.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "SAS",
    color: "orange",
    featured: true
  },
  {
    id: "17",
    title: "SAS tidsändring utan förvarning — när har du rätt till ersättning?",
    slug: "sas-tidsandring",
    excerpt: "Ändrade SAS tiden för ditt flyg? En stor ändring nära avgång kan likställas med inställt flyg. Se dina rättigheter.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "red",
    featured: false
  },
  {
    id: "18",
    title: "SAS codeshare med Lufthansa eller United — vem betalar ersättningen?",
    slug: "sas-codeshare-lufthansa-united",
    excerpt: "Köpte du av SAS men flög med Lufthansa? Lär dig regeln om 'Operating Carrier' och vem du ska kräva pengar av.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "19",
    title: "SAS high season — vad du behöver veta",
    slug: "sas-high-season",
    excerpt: "Förbered dig för SAS high season med våra tips om priser, väntetider och hur du kan spara pengar på din resa.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "20",
    title: "SAS reseroutering — hur du hittar den bästa vägen",
    slug: "sas-reseroutering",
    excerpt: "Förhindra SAS-förseningar med vår guide om hur du reserouterar din resa. Lär dig om alternativa flygplatser och tidpunkter.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "22",
    title: "Ersättning för SAS Stockholm–Chicago (ORD) — transatlantisk guide",
    slug: "sas-stockholm-chicago-ersattning",
    excerpt: "Flygförsening till Chicago med SAS? Du kan ha rätt till 600 € i ersättning. Läs vår guide om dina rättigheter på USA-flygningar.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "23",
    title: "Ersättning för SAS Stockholm–Tokyo (Haneda) — maximalt anspråk på 600 €",
    slug: "sas-stockholm-tokyo-ersattning",
    excerpt: "SAS flyg till Tokyo försenat eller inställt? Långdistans till Asien ger högsta ersättningen. Läs om dina rättigheter här.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "24",
    title: "Ersättning för SAS Göteborg–Köpenhamn–[destination] — rättigheter vid byte",
    slug: "sas-goteborg-landvetter-ersattning",
    excerpt: "Flyger du från Landvetter med byte i Köpenhamn? Missad anslutning är vanligt. Se dina rättigheter och hur du får ersättning.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "orange",
    featured: false
  },
  {
    id: "25",
    title: "Ersättning för SAS Malmö–[destination] — guide för Sturup-resenärer",
    slug: "sas-malmo-sturup-ersattning",
    excerpt: "Flyger du från Malmö Airport (Sturup) med SAS? Förseningar till Stockholm eller Arlanda kan ge rätt till ersättning. Läs mer här.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "4 min",
    category: "SAS",
    color: "orange",
    featured: false
  },
  {
    id: "26",
    title: "Ersättning för SAS Stockholm–Oslo eller Stockholm–Köpenhamn — inrikes Skandinavien",
    slug: "sas-stockholm-oslo-kopenhamn-ersattning",
    excerpt: "Pendlare i Skandinavien drabbas ofta av SAS-förseningar. Se dina rättigheter på rutterna mellan de nordiska huvudstäderna.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "27",
    title: "Ersättning för SAS på charterliknande semesterleder (Thailand, Kanarieöarna) — regler",
    slug: "sas-charter-thailand-kanarieoarna",
    excerpt: "Flyger du charter med SAS? Samma EU-regler gäller! Se hur du får upp till 600 € vid försening till solen.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "yellow",
    featured: false
  },
  {
    id: "28",
    title: "SAS Arlanda-avgångar — de mest försenade rutterna och vad du kan göra",
    slug: "sas-arlanda-avgangar",
    excerpt: "Flyger du från Arlanda med SAS? Vissa rutter är mer drabbade än andra. Se statistiken och dina rättigheter vid förseningar från Stockholm.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "29",
    title: "SAS EuroBonus-biljett och försening — kan du fortfarande kräva ersättning?",
    slug: "sas-eurobonus-ersattning",
    excerpt: "Betalade du resan med EuroBonus-poäng? Du har ändå rätt till kontantersättning vid försening. Låt inte SAS lura dig.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "4 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "30",
    title: "Hur ansöker du om ersättning från SAS steg för steg? — guide",
    slug: "hur-ansoka-ersattning-sas-steg-for-steg",
    excerpt: "Vill du kräva ersättning från SAS själv? Här är vår kompletta guide med steg-för-steg instruktioner för att lyckas med din reklamation.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "8 min",
    category: "SAS",
    color: "green",
    featured: true
  },
  {
    id: "31",
    title: "SAS dokumentation — vad du behöver för att ansöka om ersättning",
    slug: "sas-dokumentation-ersattning",
    excerpt: "Har du allt du behöver för att ansöka om ersättning från SAS? Läs om vilka dokument du ska ha med för att få snabbast svar.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "32",
    title: "SAS reklamationsbrev — hur du skriver det riktigt",
    slug: "sas-reklamationsbrev",
    excerpt: "Förvirrad av SAS:s formulär? Lär dig skriva ett effektivt reklamationsbrev som ger dig bästa chansen att vinnas.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "orange",
    featured: false
  },
  {
    id: "33",
    title: "SAS ignorerar din ansökan — vad gör du?",
    slug: "sas-ignorerar-ansokan",
    excerpt: "Har du inte fått svar på din ansökan? Lär dig hur du följer upp och vad du kan göra om SAS ignorerar din ansökan.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "red",
    featured: false
  },
  {
    id: "34",
    title: "Norwegian försenat flyg — så får du 600 € (inte CashPoints!)",
    slug: "norwegian-forsenat-flyg-ersattning",
    excerpt: "Var ditt Norwegian-flyg försenat? Du kan ha rätt till 600 € i ersättning. Läs vår guide om hur du kräver pengar från Norwegian Air.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "Norwegian",
    color: "red",
    featured: true
  },
  {
    id: "35",
    title: "Norwegian inställt flyg — dina 3 rättigheter",
    slug: "norwegian-installt-flyg-ersattning",
    excerpt: "Ställde Norwegian in ditt flyg? Du har rätt till ombokning, återbetalning OCH upp till 600 € i kompensation. Läs guiden.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "Norwegian",
    color: "red",
    featured: false
  },
  {
    id: "36",
    title: "Norwegian CashPoints vs Kontanter — acceptera aldrig poäng!",
    slug: "norwegian-cashpoints-vs-pengar",
    excerpt: "Erbjuder Norwegian CashPoints som ersättning? Varning! Det är ofta en dålig affär. Läs varför du alltid ska kräva kontanter enligt lag.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Norwegian",
    color: "orange",
    featured: true
  },
  {
    id: "37",
    title: "Ryanair försenat flyg — så får du 250 € (inte CashPoints!)",
    slug: "ryanair-forsenat-flyg-ersattning",
    excerpt: "Var ditt Ryanair-flyg försenat? Du kan ha rätt till 250 € i ersättning. Läs vår guide om hur du kräver pengar från Ryanair.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "Ryanair",
    color: "red",
    featured: true
  },
  {
    id: "38",
    title: "Ryanair inställt flyg — dina 3 rättigheter",
    slug: "ryanair-installt-flyg-ersattning",
    excerpt: "Ställde Ryanair in ditt flyg? Du har rätt till ombokning, återbetalning OCH upp till 250 € i kompensation. Läs guiden.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "Ryanair",
    color: "red",
    featured: false
  },
  {
    id: "39",
    title: "Ryanair CashPoints vs Kontanter — acceptera aldrig poäng!",
    slug: "ryanair-cashpoints-vs-pengar",
    excerpt: "Erbjuder Ryanair CashPoints som ersättning? Varning! Det är ofta en dålig affär. Läs varför du alltid ska kräva kontanter enligt lag.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Ryanair",
    color: "orange",
    featured: true
  },
  {
    id: "40",
    title: "Charterflyg försenat flyg — så får du 600 € (inte CashPoints!)",
    slug: "charter-flyg-forsenat-flyg-ersattning",
    excerpt: "Var ditt charterflyg försenat? Du kan ha rätt till 600 € i ersättning. Läs vår guide om hur du kräver pengar från charterflyg.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "Charter",
    color: "red",
    featured: true
  },
  {
    id: "41",
    title: "Charterflyg inställt flyg — dina 3 rättigheter",
    slug: "charter-flyg-installt-flyg-ersattning",
    excerpt: "Ställde charterflyg in ditt flyg? Du har rätt till ombokning, återbetalning OCH upp till 600 € i kompensation. Läs guiden.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "Charter",
    color: "red",
    featured: false
  },
  {
    id: "42",
    title: "Charterflyg CashPoints vs Kontanter — acceptera aldrig poäng!",
    slug: "charter-flyg-cashpoints-vs-pengar",
    excerpt: "Erbjuder charterflyg CashPoints som ersättning? Varning! Det är ofta en dålig affär. Läs varför du alltid ska kräva kontanter enligt lag.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Charter",
    color: "orange",
    featured: true
  },
  {
    id: "43",
    title: "Lufthansa försenat flyg — så får du 600 € (inte CashPoints!)",
    slug: "lufthansa-forsenat-flyg-ersattning",
    excerpt: "Var ditt Lufthansa-flyg försenat? Du kan ha rätt till 600 € i ersättning. Läs vår guide om hur du kräver pengar från Lufthansa.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "Lufthansa",
    color: "red",
    featured: true
  },
  {
    id: "44",
    title: "Lufthansa inställt flyg — dina 3 rättigheter",
    slug: "lufthansa-installt-flyg-ersattning",
    excerpt: "Ställde Lufthansa in ditt flyg? Du har rätt till ombokning, återbetalning OCH upp till 600 € i kompensation. Läs guiden.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "Lufthansa",
    color: "red",
    featured: false
  },
  {
    id: "45",
    title: "Lufthansa CashPoints vs Kontanter — acceptera aldrig poäng!",
    slug: "lufthansa-cashpoints-vs-pengar",
    excerpt: "Erbjuder Lufthansa CashPoints som ersättning? Varning! Det är ofta en dålig affär. Läs varför du alltid ska kräva kontanter enligt lag.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Lufthansa",
    color: "orange",
    featured: true
  },
  {
    id: "46",
    title: "EU 261/2004 — dina rättigheter som flygpassagerare",
    slug: "eu261-regler-sverige",
    excerpt: "Vad innebär EU-förordning 261/2004 för dig? Läs vår guide om den lag som ger dig rätt till upp till 600 € vid flygkaos.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "8 min",
    category: "Lag & Rätt",
    color: "blue",
    featured: true
  },
  {
    id: "47",
    title: "Extraordinära omständigheter — när slipper flygbolaget betala?",
    slug: "extraordinara-omstandigheter-sverige",
    excerpt: "Skyller flygbolaget på vädret eller tekniskt fel? Lär dig vad som verkligen räknas som extraordinära omständigheter enligt EU-domstolen.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "Lag & Rätt",
    color: "purple",
    featured: false
  },
  {
    id: "48",
    title: "Nekad ombordstigning (överbokning) — dina rättigheter och ersättning",
    slug: "nekad-ombordstigning-overbokning",
    excerpt: "Blev du nekad att gå ombord för att flyget var fullt? Överbokning ger dig rätt till omedelbar ersättning upp till 600 €.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Överbokning",
    color: "orange",
    featured: false
  },
  {
    id: "49",
    title: "Ersättning för USA-flug — vad du behöver veta",
    slug: "usa-flug-ersattning",
    excerpt: "Flyger du till USA? Lär dig om dina rättigheter, hur du ansöker och vad du kan förvänta dig.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Jobb",
    color: "gray",
    featured: false
  },
  {
    id: "50",
    title: "Ersättning för barn — vad du behöver veta",
    slug: "barn-ersattning",
    excerpt: "Flyger du med barn? Lär dig om dina rättigheter, hur du ansöker och vad du kan förvänta dig.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Jobb",
    color: "gray",
    featured: false
  },
  {
    id: "51",
    title: "Ersättning för affärsresor — vad du behöver veta",
    slug: "affarsresor-ersattning",
    excerpt: "Flyger du för affärsresor? Lär dig om dina rättigheter, hur du ansöker och vad du kan förvänta dig.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Jobb",
    color: "gray",
    featured: false
  },
  {
    id: "52",
    title: "Wizz Air i Sverige — ersättning för försenat och inställt flyg",
    slug: "wizz-air-sverige-ersattning",
    excerpt: "Flyger du med Wizz Air från Skavsta eller Malmö? Se dina rättigheter vid förseningar. Vi hjälper dig att få upp till 600 €.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "Lågprisflyg",
    color: "pink",
    featured: false
  },
  {
    id: "53",
    title: "Bromma Flygplats (BMA) — ersättning för försenat flyg",
    slug: "bromma-flygplats-ersattning",
    excerpt: "Försenad från Stockholm Bromma? Oavsett om du flög med BRA eller Brussels Airlines kan du ha rätt till ersättning. Läs mer här.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "4 min",
    category: "Svenska Flygplatser",
    color: "green",
    featured: false
  },
  {
    id: "54",
    title: "Flygförseningar i norra Sverige (Luleå, Umeå, Kiruna) — vinterregler",
    slug: "norra-sverige-flyg-vinter",
    excerpt: "Försenad p.g.a. snö eller avisning? Det räknas inte alltid som 'extraordinära omständigheter'. Se när du kan få ersättning för vinterkaos.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Vinter & Norrland",
    color: "cyan",
    featured: false
  },
  {
    id: "55",
    title: "10 år på dig att kräva ersättning! — Preskriptionstid i Sverige",
    slug: "preskriptionstid-flygersattning",
    excerpt: "Visste du att du kan kräva ersättning för flygförseningar 10 år tillbaka i tiden i Sverige? Läs om den generösa preskriptionstiden.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "4 min",
    category: "Lag & Rätt",
    color: "purple",
    featured: true
  },
  {
    id: "56",
    title: "ARN och flygersättning — varför det inte alltid räcker",
    slug: "arn-flyg-arende",
    excerpt: "Funderar du på att anmäla flygbolaget till ARN? Läs om processen, väntetiderna och varför flygbolagen ibland struntar i besluten.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "Myndigheter & ARN",
    color: "gray",
    featured: false
  },
  {
    id: "57",
    title: "Paketreselagen + Flygersättning = Dubbel kompensation?",
    slug: "paketreselagen-flygersattning",
    excerpt: "Blev charterresan förstörd? Du kan ha rätt till både prisavdrag enligt Paketreselagen OCH flygersättning enligt EU261.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Charter & Lagar",
    color: "orange",
    featured: false
  },
  {
    slug: "hur-mycket-ersattning-sas-flyg-tabell",
    title: "Hur mycket ersättning får jag för ett försenat SAS-flyg?",
    excerpt: "Snabb tabell över ersättningsnivåerna (250-600€) för SAS-förseningar.",
    date: "2025-03-06",
    readTime: "2 min",
    category: "Snabba svar",
    color: "blue",
    featured: true
  },
  {
    slug: "hur-mycket-ersattning-installt-flyg",
    title: "Hur mycket ersättning får jag för ett inställt flyg?",
    excerpt: "Reglerna för inställda flyg i Sverige. Se beloppen baserat på varsel.",
    date: "2025-03-06",
    readTime: "3 min",
    category: "Snabba svar",
    color: "blue",
    featured: false
  },
  {
    slug: "utbetalningstid-flygersattning-sverige",
    title: "Hur lång tid tar det att få flygersättning utbetald?",
    excerpt: "Väntetider för SAS, Ryanair och Norwegian. När kommer pengarna?",
    date: "2025-03-06",
    readTime: "3 min",
    category: "Snabba svar",
    color: "green",
    featured: false
  },
  {
    slug: "krava-ersattning-gammalt-flyg-3-ar",
    title: "Kan jag kräva ersättning för ett flyg för 3 år sedan?",
    excerpt: "Ja! I Sverige gäller 10 års preskriptionstid. Så här gör du.",
    date: "2025-03-06",
    readTime: "3 min",
    category: "Snabba svar",
    color: "purple",
    featured: true
  },
  {
    slug: "flygbolaget-ignorerar-ansokan",
    title: "Vad gör jag om flygbolaget ignorerar min ansökan?",
    excerpt: "Har du skickat ett krav men fått tystnad till svar? Här är stegen du ska ta när flygbolaget leker döda fisken.",
    date: "2026-03-06",
    readTime: "4 min",
    category: "Snabba svar",
    color: "red",
    featured: true
  },
  {
    slug: "vem-far-ersattningen",
    title: "Vem får ersättningen — resenären eller researrangören?",
    excerpt: "Arbetsgivare, resebyrå eller du? Vi reder ut vem som faktiskt har laglig rätt till pengarna vid en försening.",
    date: "2026-03-06",
    readTime: "3 min",
    category: "Snabba svar",
    color: "blue",
    featured: true
  },
  {
    slug: "eu261-utanfor-europa",
    title: "Gäller EU261 för flyg utanför Europa?",
    excerpt: "Resa till USA eller Asien? Se när EU:s skyddsnät gäller och när du står utan skydd.",
    date: "2026-03-06",
    readTime: "4 min",
    category: "Snabba svar",
    color: "green",
    featured: true
  },
  {
    slug: "behover-jag-ombud",
    title: "Behöver jag anlita ett ombud för att få flygersättning?",
    excerpt: "Göra det själv eller ta hjälp? Vi jämför kostnader, tid och chansen att lyckas.",
    date: "2026-03-06",
    readTime: "4 min",
    category: "Snabba svar",
    color: "gray",
    featured: true
  },
  {
    slug: "lonar-det-sig-ersattningsforetag",
    title: "Lönar det sig att använda ett ersättningsföretag för flygkrav?",
    excerpt: "Är det värt avgiften? Vi räknar på nettoersättningen med och utan hjälp.",
    date: "2026-03-06",
    readTime: "4 min",
    category: "Snabba svar",
    color: "blue",
    featured: true
  },
  {
    slug: "hur-lang-tid-ansoka-sverige",
    title: "Hur lång tid har jag på mig att ansöka om flygersättning?",
    excerpt: "2 månader eller 10 år? Vi reder ut de viktiga tidsfristerna i Sverige.",
    date: "2026-03-06",
    readTime: "3 min",
    category: "Snabba svar",
    color: "red",
    featured: true
  },
  {
    slug: "vilka-dokument-behover-jag",
    title: "Vilka dokument behöver jag för att ansöka om ersättning?",
    excerpt: "Checklista: Boardingkort, PNR och kvitton. Spara detta för att få betalt.",
    date: "2026-03-06",
    readTime: "3 min",
    category: "Snabba svar",
    color: "green",
    featured: false
  },
  {
    slug: "betalar-sas-ersattning-statistik",
    title: "Betalar SAS ersättning? Fakta, statistik och bekräftade fall",
    excerpt: "Sanningen om SAS utbetalningar. Hur ofta nekar de och hur snabba är de?",
    date: "2026-03-06",
    readTime: "4 min",
    category: "Snabba svar",
    color: "blue",
    featured: true
  },
  {
    id: "arlanda-forsenat-installat-flyg-guide",
    title: "Försening eller inställt flyg på Arlanda (ARN) — Passagerarrättigheter 2025",
    slug: "arlanda-forsenat-installat-flyg-guide",
    category: "airport",
    airportCode: "ARN",
    airportName: "Stockholm Arlanda",
    flag: "🇸🇪",
    wordCount: 4200,
    readTime: 14,
    excerpt: "Komplett guide till dina rättigheter vid försening eller inställt flyg från Stockholm Arlanda. Få upp till 600 € ersättning enligt EU261.",
    publishDate: "2026-03-07",
    featured: true,
    color: "blue",
    schema: {
      faqItems: [
        {
          question: "Hur lång försening krävs för ersättning från Arlanda?",
          answer: "Du har rätt till ersättning om ditt flyg från Arlanda anländer minst 3 timmar försenat till slutdestinationen. Beloppet beror på flygsträckan: 250 € för flyg under 1500 km, 400 € för flyg 1500-3500 km inom EU, och 600 € för flyg över 3500 km eller utanför EU."
        },
        {
          question: "Gäller EU261 för alla flyg från Arlanda?",
          answer: "Ja, EU261 gäller för alla flyg som avgår från Arlanda (Stockholm Arlanda Airport), oavsett flygbolagets nationalitet. Det gäller även för ankommande flyg till Arlanda om flygbolaget är baserat i EU."
        }
      ]
    }
  },
  {
    id: "missat-anslutningsflyg-arlanda",
    title: "Missat anslutningsflyg på Arlanda (ARN) — Ersättningsguide steg för steg 2025",
    slug: "missat-anslutningsflyg-arlanda",
    category: "airport",
    airportCode: "ARN",
    airportName: "Stockholm Arlanda",
    flag: "🇸🇪",
    wordCount: 3800,
    readTime: 12,
    excerpt: "Missade du ditt anslutningsflyg på Stockholm Arlanda? Få upp till 600 € ersättning enligt EU261. Komplett guide med juridiska tips.",
    publishDate: "2026-03-07",
    featured: true,
    color: "blue",
    schema: {
      faqItems: [
        {
          question: "Hur mycket ersättning får jag om jag missar anslutningsflyg på Arlanda?",
          answer: "Ersättningen beror på den totala sträckan från ursprungsflygplatsen till slutdestinationen. Du kan få 250 € (under 1500 km), 400 € (1500-3500 km) eller 600 € (över 3500 km). Avgörande är att du anländer minst 3 timmar försenat till slutmålet."
        },
        {
          question: "Gäller ersättning om jag bokade flygningarna separat?",
          answer: "Nej, EU261-ersättning gäller endast när båda flygningarna är bokade som en enda bokning (samma PNR-nummer)."
        }
      ]
    }
  },
  {
    id: "arlanda-forsenade-flygbolag-statistik",
    title: "Mest försenade flygbolagen på Arlanda 2025 — Statistik och ersättningsråd",
    slug: "arlanda-forsenade-flygbolag-statistik",
    category: "airport",
    airportCode: "ARN",
    airportName: "Stockholm Arlanda",
    flag: "🇸🇪",
    wordCount: 4600,
    readTime: 16,
    excerpt: "Vilka flygbolag och rutter från Stockholm Arlanda har flest förseningar? Se aktuell statistik och lär dig maximera dina chanser till 600 € ersättning.",
    publishDate: "2026-03-07",
    featured: true,
    color: "blue",
    schema: {
      faqItems: [
        {
          question: "Vilket flygbolag på Arlanda har flest förseningar?",
          answer: "Enligt data från 2024 har Norwegian och Wizz Air högst andel förseningar på Arlanda med cirka 25-30% av flygningarna försenade över 15 minuter."
        },
        {
          question: "Vilka rutter från Arlanda är mest försenade?",
          answer: "De mest försenade rutterna är: Stockholm–London (22%), Stockholm–Oslo/Köpenhamn (20%), Stockholm–Bangkok/Phuket (18%), och Stockholm–New York (17%)."
        }
      ]
    }
  },
  {
    id: "arlanda-new-york-forsening-600-euro",
    title: "Arlanda till New York försenat? Få 600 € (Krav och Guide)",
    slug: "arlanda-new-york-forsening-600-euro",
    category: "airport",
    airportCode: "ARN",
    airportName: "Stockholm Arlanda",
    flag: "🇸🇪",
    wordCount: 2200,
    readTime: 11,
    excerpt: "Har ditt flyg från Stockholm Arlanda (ARN) till New York (EWR/JFK) blivit försenat? Lär dig hur du säkrar 600 € ersättning enligt EU261.",
    publishDate: "2026-03-07",
    featured: false,
    color: "blue"
  },
  {
    id: "arlanda-london-uk261-eu261-brexit",
    title: "Arlanda till London försenat? EU261 vs UK261 efter Brexit",
    slug: "arlanda-london-uk261-eu261-brexit",
    category: "airport",
    airportCode: "ARN",
    airportName: "Stockholm Arlanda",
    flag: "🇸🇪",
    wordCount: 1900,
    readTime: 9,
    excerpt: "Flygproblem mellan Stockholm och London? Förstå dina rättigheter efter Brexit och lär dig hur du kräver ersättning.",
    publishDate: "2026-03-07",
    featured: false,
    color: "blue"
  },
  {
    id: "arlanda-dubai-eu261-ersattning",
    title: "Arlanda till Dubai försenat? När gäller EU261 för Mellanösternflyg",
    slug: "arlanda-dubai-eu261-ersattning",
    category: "airport",
    airportCode: "ARN",
    airportName: "Stockholm Arlanda",
    flag: "🇸🇪",
    wordCount: 1950,
    readTime: 10,
    excerpt: "Emirates eller Norwegian försenat mellan Stockholm och Dubai? Lär dig exakt när du kan kräva 600 € i ersättning enligt EU-lag.",
    publishDate: "2026-03-07",
    featured: false,
    color: "blue"
  },
  {
    id: "arlanda-massavbokningar-kris-rattigheter",
    title: "Massavbokningar på Arlanda (ARN) — Passagerares rättigheter vid kris",
    slug: "arlanda-massavbokningar-kris-rattigheter",
    category: "airport",
    airportCode: "ARN",
    airportName: "Stockholm Arlanda",
    flag: "🇸🇪",
    wordCount: 2100,
    readTime: 10,
    excerpt: "Inställda flyg i massor på Stockholm Arlanda? Lär dig dina rättigheter vid strejk, väderkaos eller IT-problem.",
    publishDate: "2026-03-07",
    featured: false,
    color: "red"
  },
  {
    id: "landvetter-forsenat-installt-flyg-guide",
    title: "Försening eller inställt flyg på Landvetter (GOT) — Komplett guide",
    slug: "landvetter-forsenat-installt-flyg-guide",
    category: "airport",
    airportCode: "GOT",
    airportName: "Göteborg Landvetter",
    flag: "🇸🇪",
    wordCount: 2500,
    readTime: 12,
    excerpt: "Drabbats av ett försenat eller inställt flyg från Göteborg Landvetter? Få reda på hur du kräver upp till 600 € i ersättning enligt EU261.",
    publishDate: "2026-03-07",
    featured: true,
    color: "blue"
  },
  {
    id: "sas-norwegian-goteborg-forseningar-ersattning",
    title: "SAS och Norwegian från Göteborg — Förseningar & Ersättning",
    slug: "sas-norwegian-goteborg-forseningar-ersattning",
    category: "airport",
    airportCode: "GOT",
    airportName: "Göteborg Landvetter",
    flag: "🇸🇪",
    wordCount: 2200,
    readTime: 11,
    excerpt: "Flyger du SAS eller Norwegian från Göteborg? Så här hanterar du inställda och försenade flyg, och säkrar din ekonomiska kompensation.",
    publishDate: "2026-03-07",
    featured: false,
    color: "blue"
  },
  {
    id: "ryanair-wizz-air-goteborg-rattigheter",
    title: "Ryanair och Wizz Air från Göteborg — Rättigheter och Ersättning 2025",
    slug: "ryanair-wizz-air-goteborg-rattigheter",
    category: "airport",
    airportCode: "GOT",
    airportName: "Göteborg Landvetter",
    flag: "🇸🇪",
    wordCount: 2300,
    readTime: 11,
    excerpt: "Problem med Ryanair eller Wizz Air från Landvetter? Lär dig dina passagerarrättigheter och hur du tvingar lågprisbolagen att betala EU261-ersättning.",
    publishDate: "2026-03-07",
    featured: false,
    color: "blue"
  },
  {
    id: "behover-jag-ombud",
    title: "Behöver jag ett ombud eller advokat för att få ersättning?",
    slug: "behover-jag-ombud",
    category: "longtail",
    wordCount: 1500,
    readTime: 6,
    excerpt: "Går det att kräva ersättning själv, eller måste man använda företag som ClaimWinger? Fördelar och nackdelar.",
    publishDate: "2025-02-28",
    featured: false,
    color: "blue"
  },
  {
    id: "lonar-det-sig-ersattningsforetag",
    title: "Lönar det sig att använda ett ersättningsföretag?",
    slug: "lonar-det-sig-ersattningsforetag",
    category: "longtail",
    wordCount: 1600,
    readTime: 7,
    excerpt: "När är det värt att betala en provision för att få hjälp med sitt ärende? Jämförelse av olika tjänster.",
    publishDate: "2025-02-28",
    featured: false,
    color: "blue"
  },
  {
    id: "hur-lang-tid-ansoka-sverige",
    title: "Hur lång tid har jag på mig att ansöka om ersättning i Sverige?",
    slug: "hur-lang-tid-ansoka-sverige",
    category: "longtail",
    wordCount: 1200,
    readTime: 5,
    excerpt: "Preskriptionstiden skiljer sig mellan olika länder. I Sverige har du ett visst antal år på dig - se vad som gäller.",
    publishDate: "2025-02-28",
    featured: false,
    color: "blue"
  },
  {
    id: "vilka-dokument-behover-jag",
    title: "Vilka dokument behöver jag spara vid en försening?",
    slug: "vilka-dokument-behover-jag",
    category: "longtail",
    wordCount: 1400,
    readTime: 6,
    excerpt: "En checklista på allt du måste spara på flygplatsen för att säkerställa att du får din ersättning utbetald.",
    publishDate: "2025-02-28",
    featured: false,
    color: "blue"
  },
  {
    id: "betalar-sas-ersattning-statistik",
    title: "Hur ofta betalar SAS ut ersättning utan strid?",
    slug: "betalar-sas-ersattning-statistik",
    category: "longtail",
    wordCount: 1800,
    readTime: 8,
    excerpt: "Statistik på hur flygbolag som SAS agerar vid ersättningskrav - hur stor chans är det att du får dina pengar direkt?",
    publishDate: "2025-02-28",
    featured: false,
    color: "blue"
  }
];