import { BlogArticle } from "@/lib/blogArticles";

export const blogArticlesSv: BlogArticle[] = [
  {
    id: "1",
    title: "Ersättning för försenat SAS-flyg — komplett guide 2025",
    slug: "sas-forsenat-flyg-ersattning",
    excerpt: "Var ditt SAS-flyg försenat? Läs vår kompletta guide om hur du får upp till 600 € i ersättning från SAS. Regler, belopp och steg-för-steg instruktioner.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "8 min",
    category: "SAS",
    color: "blue",
    featured: true
  },
  {
    id: "2",
    title: "SAS ställde in flyget — hur får du upp till 600 € i ersättning?",
    slug: "sas-installt-flyg-ersattning",
    excerpt: "Blev ditt SAS-flyg inställt? Läs om dina rättigheter till ombokning, återbetalning och kompensation upp till 600 €. Guide för drabbade passagerare.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "9 min",
    category: "SAS",
    color: "red",
    featured: true
  },
  {
    id: "3",
    title: "SAS nekade ersättning — vad gör du härnäst?",
    slug: "sas-nekade-ersattning",
    excerpt: "Har SAS nekat din ersättning? Ge inte upp! Många avslag är felaktiga. Läs vår guide om hur du överklagar och vinner mot SAS.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "SAS",
    color: "orange",
    featured: false
  },
  {
    id: "4",
    title: "SAS erbjuder voucher istället för pengar — måste du acceptera det?",
    slug: "sas-voucher-eller-pengar",
    excerpt: "Erbjuder SAS en voucher? Läs varför kontanter nästan alltid är bättre och hur du tackar nej på rätt sätt enligt EU-lag.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "5",
    title: "Hur lång tid tar det för SAS att betala ersättning?",
    slug: "sas-utbetalningstid-ersattning",
    excerpt: "Väntar du på pengar från SAS? Här är den brutala sanningen om väntetider 2025 och tips för att snabba på din utbetalning.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "green",
    featured: false
  },
  {
    id: "6",
    title: "Hur mycket ersättning kan du kräva från SAS? (Tabell)",
    slug: "sas-ersattning-belopp-tabell",
    excerpt: "250 €, 400 € eller 600 €? Se vår enkla tabell baserad på flygsträcka och räkna ut exakt vad SAS är skyldiga dig.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "4 min",
    category: "SAS",
    color: "yellow",
    featured: false
  },
  {
    id: "7",
    title: "Ersättning vs. återbetalning av biljett hos SAS — vad är skillnaden?",
    slug: "sas-ersattning-vs-aterbetalning",
    excerpt: "Blandar du ihop återbetalning med ersättning? Läs om när du kan få båda — pengarna tillbaka för biljetten PLUS upp till 600 € i skadestånd.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "green",
    featured: false
  },
  {
    id: "8",
    title: "SAS försening vs. inställt flyg — olika regler, olika ersättning",
    slug: "sas-forsening-vs-installt-flyg",
    excerpt: "Är ditt flyg försenat eller inställt? Gränsen är hårfin men viktig. Vi förklarar skillnaderna i dina rättigheter och hur du maximerar din ersättning.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "9",
    title: "SAS försenat mer än 3 timmar — dina rättigheter steg för steg",
    slug: "sas-forsenat-mer-an-3-timmar",
    excerpt: "Har ditt SAS-flyg landat mer än 3 timmar för sent? Läs vår guide om hur du säkrar upp till 600 € i ersättning. Steg-för-steg instruktioner.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "blue",
    featured: true
  },
  {
    id: "10",
    title: "SAS ställde in flyget mindre än 14 dagar före avgång — ersättning",
    slug: "sas-installt-flyg-14-dagar",
    excerpt: "14-dagarsregeln är avgörande. Fick du veta om inställningen för sent? Se hur du kräver ersättning från SAS.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "SAS",
    color: "red",
    featured: false
  },
  {
    id: "11",
    title: "SAS ställde in flyget mindre än 7 dagar före avgång — sista minuten",
    slug: "sas-installt-flyg-7-dagar",
    excerpt: "Inställt sista veckan? Kraven på SAS är stenhårda. Se varför du nästan alltid har rätt till ersättning vid sena besked.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "red",
    featured: false
  },
  {
    id: "12",
    title: "SAS försenat mer än 3 timmar — dina rättigheter steg för steg",
    slug: "sas-forsenat-mer-an-3-timmar",
    excerpt: "Har ditt SAS-flyg landat mer än 3 timmar för sent? Läs vår guide om hur du säkrar upp till 600 € i ersättning. Steg-för-steg instruktioner.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "blue",
    featured: true
  },
  {
    id: "13",
    title: "SAS ställde in flyget mindre än 14 dagar före avgång — ersättning",
    slug: "sas-installt-flyg-14-dagar",
    excerpt: "14-dagarsregeln är avgörande. Fick du veta om inställningen för sent? Se hur du kräver ersättning från SAS.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "SAS",
    color: "red",
    featured: false
  },
  {
    id: "14",
    title: "SAS ställde in flyget mindre än 7 dagar före avgång — sista minuten",
    slug: "sas-installt-flyg-7-dagar",
    excerpt: "Inställt sista veckan? Kraven på SAS är stenhårda. Se varför du nästan alltid har rätt till ersättning vid sena besked.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "red",
    featured: false
  },
  {
    id: "16",
    title: "Missat anslutningsflyg på grund av SAS-försening — vem betalar?",
    slug: "sas-missat-anslutningsflyg",
    excerpt: "Missade du ditt nästa flyg p.g.a. SAS? Om du har en genomgående biljett ansvarar SAS för hela resan. Läs om ersättning.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "SAS",
    color: "orange",
    featured: true
  },
  {
    id: "17",
    title: "SAS tidsändring utan förvarning — när har du rätt till ersättning?",
    slug: "sas-tidsandring",
    excerpt: "Ändrade SAS tiden för ditt flyg? En stor ändring nära avgång kan likställas med inställt flyg. Se dina rättigheter.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "red",
    featured: false
  },
  {
    id: "18",
    title: "SAS codeshare med Lufthansa eller United — vem betalar ersättningen?",
    slug: "sas-codeshare-lufthansa-united",
    excerpt: "Köpte du av SAS men flög med Lufthansa? Lär dig regeln om 'Operating Carrier' och vem du ska kräva pengar av.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "19",
    title: "SAS high season — vad du behöver veta",
    slug: "sas-high-season",
    excerpt: "Förbered dig för SAS high season med våra tips om priser, väntetider och hur du kan spara pengar på din resa.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "20",
    title: "SAS reseroutering — hur du hittar den bästa vägen",
    slug: "sas-reseroutering",
    excerpt: "Förhindra SAS-förseningar med vår guide om hur du reserouterar din resa. Lär dig om alternativa flygplatser och tidpunkter.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "22",
    title: "Ersättning för SAS Stockholm–Chicago (ORD) — transatlantisk guide",
    slug: "sas-stockholm-chicago-ersattning",
    excerpt: "Flygförsening till Chicago med SAS? Du kan ha rätt till 600 € i ersättning. Läs vår guide om dina rättigheter på USA-flygningar.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "23",
    title: "Ersättning för SAS Stockholm–Tokyo (Haneda) — maximalt anspråk på 600 €",
    slug: "sas-stockholm-tokyo-ersattning",
    excerpt: "SAS flyg till Tokyo försenat eller inställt? Långdistans till Asien ger högsta ersättningen. Läs om dina rättigheter här.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "24",
    title: "Ersättning för SAS Göteborg–Köpenhamn–[destination] — rättigheter vid byte",
    slug: "sas-goteborg-landvetter-ersattning",
    excerpt: "Flyger du från Landvetter med byte i Köpenhamn? Missad anslutning är vanligt. Se dina rättigheter och hur du får ersättning.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "orange",
    featured: false
  },
  {
    id: "25",
    title: "Ersättning för SAS Malmö–[destination] — guide för Sturup-resenärer",
    slug: "sas-malmo-sturup-ersattning",
    excerpt: "Flyger du från Malmö Airport (Sturup) med SAS? Förseningar till Stockholm eller Arlanda kan ge rätt till ersättning. Läs mer här.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "4 min",
    category: "SAS",
    color: "orange",
    featured: false
  },
  {
    id: "26",
    title: "Ersättning för SAS Stockholm–Oslo eller Stockholm–Köpenhamn — inrikes Skandinavien",
    slug: "sas-stockholm-oslo-kopenhamn-ersattning",
    excerpt: "Pendlare i Skandinavien drabbas ofta av SAS-förseningar. Se dina rättigheter på rutterna mellan de nordiska huvudstäderna.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "27",
    title: "Ersättning för SAS på charterliknande semesterleder (Thailand, Kanarieöarna) — regler",
    slug: "sas-charter-thailand-kanarieoarna",
    excerpt: "Flyger du charter med SAS? Samma EU-regler gäller! Se hur du får upp till 600 € vid försening till solen.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "yellow",
    featured: false
  },
  {
    id: "28",
    title: "SAS Arlanda-avgångar — de mest försenade rutterna och vad du kan göra",
    slug: "sas-arlanda-avgangar",
    excerpt: "Flyger du från Arlanda med SAS? Vissa rutter är mer drabbade än andra. Se statistiken och dina rättigheter vid förseningar från Stockholm.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "29",
    title: "SAS EuroBonus-biljett och försening — kan du fortfarande kräva ersättning?",
    slug: "sas-eurobonus-ersattning",
    excerpt: "Betalade du resan med EuroBonus-poäng? Du har ändå rätt till kontantersättning vid försening. Låt inte SAS lura dig.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "4 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "30",
    title: "Hur ansöker du om ersättning från SAS steg för steg? — guide",
    slug: "hur-ansoka-ersattning-sas-steg-for-steg",
    excerpt: "Vill du kräva ersättning från SAS själv? Här är vår kompletta guide med steg-för-steg instruktioner för att lyckas med din reklamation.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "8 min",
    category: "SAS",
    color: "green",
    featured: true
  },
  {
    id: "31",
    title: "SAS dokumentation — vad du behöver för att ansöka om ersättning",
    slug: "sas-dokumentation-ersattning",
    excerpt: "Har du allt du behöver för att ansöka om ersättning från SAS? Läs om vilka dokument du ska ha med för att få snabbast svar.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "blue",
    featured: false
  },
  {
    id: "32",
    title: "SAS reklamationsbrev — hur du skriver det riktigt",
    slug: "sas-reklamationsbrev",
    excerpt: "Förvirrad av SAS:s formulär? Lär dig skriva ett effektivt reklamationsbrev som ger dig bästa chansen att vinnas.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "SAS",
    color: "orange",
    featured: false
  },
  {
    id: "33",
    title: "SAS ignorerar din ansökan — vad gör du?",
    slug: "sas-ignorerar-ansokan",
    excerpt: "Har du inte fått svar på din ansökan? Lär dig hur du följer upp och vad du kan göra om SAS ignorerar din ansökan.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "SAS",
    color: "red",
    featured: false
  },
  {
    id: "34",
    title: "Norwegian försenat flyg — så får du 600 € (inte CashPoints!)",
    slug: "norwegian-forsenat-flyg-ersattning",
    excerpt: "Var ditt Norwegian-flyg försenat? Du kan ha rätt till 600 € i ersättning. Läs vår guide om hur du kräver pengar från Norwegian Air.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "Norwegian",
    color: "red",
    featured: true
  },
  {
    id: "35",
    title: "Norwegian inställt flyg — dina 3 rättigheter",
    slug: "norwegian-installt-flyg-ersattning",
    excerpt: "Ställde Norwegian in ditt flyg? Du har rätt till ombokning, återbetalning OCH upp till 600 € i kompensation. Läs guiden.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "Norwegian",
    color: "red",
    featured: false
  },
  {
    id: "36",
    title: "Norwegian CashPoints vs Kontanter — acceptera aldrig poäng!",
    slug: "norwegian-cashpoints-vs-pengar",
    excerpt: "Erbjuder Norwegian CashPoints som ersättning? Varning! Det är ofta en dålig affär. Läs varför du alltid ska kräva kontanter enligt lag.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Norwegian",
    color: "orange",
    featured: true
  },
  {
    id: "37",
    title: "Ryanair försenat flyg — så får du 250 € (inte CashPoints!)",
    slug: "ryanair-forsenat-flyg-ersattning",
    excerpt: "Var ditt Ryanair-flyg försenat? Du kan ha rätt till 250 € i ersättning. Läs vår guide om hur du kräver pengar från Ryanair.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "Ryanair",
    color: "red",
    featured: true
  },
  {
    id: "38",
    title: "Ryanair inställt flyg — dina 3 rättigheter",
    slug: "ryanair-installt-flyg-ersattning",
    excerpt: "Ställde Ryanair in ditt flyg? Du har rätt till ombokning, återbetalning OCH upp till 250 € i kompensation. Läs guiden.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "Ryanair",
    color: "red",
    featured: false
  },
  {
    id: "39",
    title: "Ryanair CashPoints vs Kontanter — acceptera aldrig poäng!",
    slug: "ryanair-cashpoints-vs-pengar",
    excerpt: "Erbjuder Ryanair CashPoints som ersättning? Varning! Det är ofta en dålig affär. Läs varför du alltid ska kräva kontanter enligt lag.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Ryanair",
    color: "orange",
    featured: true
  },
  {
    id: "40",
    title: "Charterflyg försenat flyg — så får du 600 € (inte CashPoints!)",
    slug: "charter-flyg-forsenat-flyg-ersattning",
    excerpt: "Var ditt charterflyg försenat? Du kan ha rätt till 600 € i ersättning. Läs vår guide om hur du kräver pengar från charterflyg.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "Charter",
    color: "red",
    featured: true
  },
  {
    id: "41",
    title: "Charterflyg inställt flyg — dina 3 rättigheter",
    slug: "charter-flyg-installt-flyg-ersattning",
    excerpt: "Ställde charterflyg in ditt flyg? Du har rätt till ombokning, återbetalning OCH upp till 600 € i kompensation. Läs guiden.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "Charter",
    color: "red",
    featured: false
  },
  {
    id: "42",
    title: "Charterflyg CashPoints vs Kontanter — acceptera aldrig poäng!",
    slug: "charter-flyg-cashpoints-vs-pengar",
    excerpt: "Erbjuder charterflyg CashPoints som ersättning? Varning! Det är ofta en dålig affär. Läs varför du alltid ska kräva kontanter enligt lag.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Charter",
    color: "orange",
    featured: true
  },
  {
    id: "43",
    title: "Lufthansa försenat flyg — så får du 600 € (inte CashPoints!)",
    slug: "lufthansa-forsenat-flyg-ersattning",
    excerpt: "Var ditt Lufthansa-flyg försenat? Du kan ha rätt till 600 € i ersättning. Läs vår guide om hur du kräver pengar från Lufthansa.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "Lufthansa",
    color: "red",
    featured: true
  },
  {
    id: "44",
    title: "Lufthansa inställt flyg — dina 3 rättigheter",
    slug: "lufthansa-installt-flyg-ersattning",
    excerpt: "Ställde Lufthansa in ditt flyg? Du har rätt till ombokning, återbetalning OCH upp till 600 € i kompensation. Läs guiden.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "Lufthansa",
    color: "red",
    featured: false
  },
  {
    id: "45",
    title: "Lufthansa CashPoints vs Kontanter — acceptera aldrig poäng!",
    slug: "lufthansa-cashpoints-vs-pengar",
    excerpt: "Erbjuder Lufthansa CashPoints som ersättning? Varning! Det är ofta en dålig affär. Läs varför du alltid ska kräva kontanter enligt lag.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Lufthansa",
    color: "orange",
    featured: true
  },
  {
    id: "46",
    title: "EU 261/2004 — dina rättigheter som flygpassagerare",
    slug: "eu261-regler-sverige",
    excerpt: "Vad innebär EU-förordning 261/2004 för dig? Läs vår guide om den lag som ger dig rätt till upp till 600 € vid flygkaos.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "8 min",
    category: "Lag & Rätt",
    color: "blue",
    featured: true
  },
  {
    id: "47",
    title: "Extraordinära omständigheter — när slipper flygbolaget betala?",
    slug: "extraordinara-omstandigheter-sverige",
    excerpt: "Skyller flygbolaget på vädret eller tekniskt fel? Lär dig vad som verkligen räknas som extraordinära omständigheter enligt EU-domstolen.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "7 min",
    category: "Lag & Rätt",
    color: "purple",
    featured: false
  },
  {
    id: "48",
    title: "Nekad ombordstigning (överbokning) — dina rättigheter och ersättning",
    slug: "nekad-ombordstigning-overbokning",
    excerpt: "Blev du nekad att gå ombord för att flyget var fullt? Överbokning ger dig rätt till omedelbar ersättning upp till 600 €.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Överbokning",
    color: "orange",
    featured: false
  },
  {
    id: "49",
    title: "Ersättning för USA-flug — vad du behöver veta",
    slug: "usa-flug-ersattning",
    excerpt: "Flyger du till USA? Lär dig om dina rättigheter, hur du ansöker och vad du kan förvänta dig.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Jobb",
    color: "gray",
    featured: false
  },
  {
    id: "50",
    title: "Ersättning för barn — vad du behöver veta",
    slug: "barn-ersattning",
    excerpt: "Flyger du med barn? Lär dig om dina rättigheter, hur du ansöker och vad du kan förvänta dig.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Jobb",
    color: "gray",
    featured: false
  },
  {
    id: "51",
    title: "Ersättning för affärsresor — vad du behöver veta",
    slug: "affarsresor-ersattning",
    excerpt: "Flyger du för affärsresor? Lär dig om dina rättigheter, hur du ansöker och vad du kan förvänta dig.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Jobb",
    color: "gray",
    featured: false
  },
  {
    id: "52",
    title: "Wizz Air i Sverige — ersättning för försenat och inställt flyg",
    slug: "wizz-air-sverige-ersattning",
    excerpt: "Flyger du med Wizz Air från Skavsta eller Malmö? Se dina rättigheter vid förseningar. Vi hjälper dig att få upp till 600 €.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "Lågprisflyg",
    color: "pink",
    featured: false
  },
  {
    id: "53",
    title: "Bromma Flygplats (BMA) — ersättning för försenat flyg",
    slug: "bromma-flygplats-ersattning",
    excerpt: "Försenad från Stockholm Bromma? Oavsett om du flög med BRA eller Brussels Airlines kan du ha rätt till ersättning. Läs mer här.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "4 min",
    category: "Svenska Flygplatser",
    color: "green",
    featured: false
  },
  {
    id: "54",
    title: "Flygförseningar i norra Sverige (Luleå, Umeå, Kiruna) — vinterregler",
    slug: "norra-sverige-flyg-vinter",
    excerpt: "Försenad p.g.a. snö eller avisning? Det räknas inte alltid som 'extraordinära omständigheter'. Se när du kan få ersättning för vinterkaos.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Vinter & Norrland",
    color: "cyan",
    featured: false
  },
  {
    id: "55",
    title: "10 år på dig att kräva ersättning! — Preskriptionstid i Sverige",
    slug: "preskriptionstid-flygersattning",
    excerpt: "Visste du att du kan kräva ersättning för flygförseningar 10 år tillbaka i tiden i Sverige? Läs om den generösa preskriptionstiden.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "4 min",
    category: "Lag & Rätt",
    color: "purple",
    featured: true
  },
  {
    id: "56",
    title: "ARN och flygersättning — varför det inte alltid räcker",
    slug: "arn-flyg-arende",
    excerpt: "Funderar du på att anmäla flygbolaget till ARN? Läs om processen, väntetiderna och varför flygbolagen ibland struntar i besluten.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "6 min",
    category: "Myndigheter & ARN",
    color: "gray",
    featured: false
  },
  {
    id: "57",
    title: "Paketreselagen + Flygersättning = Dubbel kompensation?",
    slug: "paketreselagen-flygersattning",
    excerpt: "Blev charterresan förstörd? Du kan ha rätt till både prisavdrag enligt Paketreselagen OCH flygersättning enligt EU261.",
    date: "2025-03-06",
    publishDate: "2025-03-06",
    readTime: "5 min",
    category: "Charter & Lagar",
    color: "orange",
    featured: false
  },
  {
    id: "hur-mycket-ersattning-sas-flyg-tabell",
    title: "Hur mycket ersättning får jag för ett försenat SAS-flyg?",
    slug: "hur-mycket-ersattning-sas-flyg-tabell",
    excerpt: "Snabb tabell över ersättningsnivåerna (250-600€) för SAS-förseningar.",
    date: "2025-03-06",
    readTime: "2 min",
    category: "Snabba svar",
    color: "blue",
    featured: true
  },
  {
    id: "hur-mycket-ersattning-installt-flyg",
    title: "Hur mycket ersättning får jag för ett inställt flyg?",
    slug: "hur-mycket-ersattning-installt-flyg",
    excerpt: "Reglerna för inställda flyg i Sverige. Se beloppen baserat på varsel.",
    date: "2025-03-06",
    readTime: "3 min",
    category: "Snabba svar",
    color: "blue",
    featured: false
  },
  {
    id: "utbetalningstid-flygersattning-sverige",
    title: "Hur lång tid tar det att få flygersättning utbetald?",
    slug: "utbetalningstid-flygersattning-sverige",
    excerpt: "Väntetider för SAS, Ryanair och Norwegian. När kommer pengarna?",
    date: "2025-03-06",
    readTime: "3 min",
    category: "Snabba svar",
    color: "green",
    featured: false
  },
  {
    id: "krava-ersattning-gammalt-flyg-3-ar",
    title: "Kan jag kräva ersättning för ett flyg för 3 år sedan?",
    slug: "krava-ersattning-gammalt-flyg-3-ar",
    excerpt: "Ja! I Sverige gäller 10 års preskriptionstid. Så här gör du.",
    date: "2025-03-06",
    readTime: "3 min",
    category: "Snabba svar",
    color: "purple",
    featured: true
  },
  {
    id: "flygbolaget-ignorerar-ansokan",
    title: "Vad gör jag om flygbolaget ignorerar min ansökan?",
    slug: "flygbolaget-ignorerar-ansokan",
    excerpt: "Har du skickat ett krav men fått tystnad till svar? Här är stegen du ska ta när flygbolaget leker döda fisken.",
    date: "2026-03-06",
    readTime: "4 min",
    category: "Snabba svar",
    color: "red",
    featured: true
  },
  {
    id: "vem-far-ersattningen",
    title: "Vem får ersättningen — resenären eller researrangören?",
    slug: "vem-far-ersattningen",
    excerpt: "Arbetsgivare, resebyrå eller du? Vi reder ut vem som faktiskt har laglig rätt till pengarna vid en försening.",
    date: "2026-03-06",
    readTime: "3 min",
    category: "Snabba svar",
    color: "blue",
    featured: true
  },
  {
    id: "eu261-utanfor-europa",
    title: "Gäller EU261 för flyg utanför Europa?",
    slug: "eu261-utanfor-europa",
    excerpt: "Resa till USA eller Asien? Se när EU:s skyddsnät gäller och när du står utan skydd.",
    date: "2026-03-06",
    readTime: "4 min",
    category: "Snabba svar",
    color: "green",
    featured: true
  },
  {
    id: "behover-jag-ombud",
    title: "Behöver jag anlita ett ombud för att få flygersättning?",
    slug: "behover-jag-ombud",
    excerpt: "Göra det själv eller ta hjälp? Vi jämför kostnader, tid och chansen att lyckas.",
    date: "2026-03-06",
    readTime: "4 min",
    category: "Snabba svar",
    color: "gray",
    featured: true
  },
  {
    id: "lonar-det-sig-ersattningsforetag",
    title: "Lönar det sig att använda ett ersättningsföretag för flygkrav?",
    slug: "lonar-det-sig-ersattningsforetag",
    excerpt: "Är det värt avgiften? Vi räknar på nettoersättningen med och utan hjälp.",
    date: "2026-03-06",
    readTime: "4 min",
    category: "Snabba svar",
    color: "blue",
    featured: true
  },
  {
    id: "hur-lang-tid-ansoka-sverige",
    title: "Hur lång tid har jag på mig att ansöka om flygersättning?",
    slug: "hur-lang-tid-ansoka-sverige",
    excerpt: "2 månader eller 10 år? Vi reder ut de viktiga tidsfristerna i Sverige.",
    date: "2026-03-06",
    readTime: "3 min",
    category: "Snabba svar",
    color: "red",
    featured: true
  },
  {
    id: "vilka-dokument-behover-jag",
    title: "Vilka dokument behöver jag för att ansöka om ersättning?",
    slug: "vilka-dokument-behover-jag",
    excerpt: "Checklista: Boardingkort, PNR och kvitton. Spara detta för att få betalt.",
    date: "2026-03-06",
    readTime: "3 min",
    category: "Snabba svar",
    color: "green",
    featured: false
  },
  {
    id: "betalar-sas-ersattning-statistik",
    title: "Betalar SAS ersättning? Fakta, statistik och bekräftade fall",
    slug: "betalar-sas-ersattning-statistik",
    excerpt: "Sanningen om SAS utbetalningar. Hur ofta nekar de och hur snabba är de?",
    date: "2026-03-06",
    readTime: "4 min",
    category: "Snabba svar",
    color: "blue",
    featured: true
  },
  {
    id: "arlanda-forsenat-installat-flyg-guide",
    title: "Försening eller inställt flyg på Arlanda (ARN) — Passagerarrättigheter 2025",
    slug: "arlanda-forsenat-installat-flyg-guide",
    category: "Stockholm Arlanda",
    date: "2026-03-07",
    publishDate: "2026-03-07",
    readTime: "14 min",
    excerpt: "Komplett guide till dina rättigheter vid försening eller inställt flyg från Stockholm Arlanda. Få upp till 600 € ersättning enligt EU261.",
    featured: true,
    color: "blue"
  },
  {
    id: "missat-anslutningsflyg-arlanda",
    title: "Missat anslutningsflyg på Arlanda (ARN) — Ersättningsguide steg för steg 2025",
    slug: "missat-anslutningsflyg-arlanda",
    category: "Stockholm Arlanda",
    date: "2026-03-07",
    publishDate: "2026-03-07",
    readTime: "12 min",
    excerpt: "Missade du ditt anslutningsflyg på Stockholm Arlanda? Få upp till 600 € ersättning enligt EU261. Komplett guide med juridiska tips.",
    featured: true,
    color: "blue"
  },
  {
    id: "arlanda-forsenade-flygbolag-statistik",
    title: "Mest försenade flygbolagen på Arlanda 2025 — Statistik och ersättningsråd",
    slug: "arlanda-forsenade-flygbolag-statistik",
    category: "Arlanda",
    excerpt: "Vilka flygbolag har flest förseningar på Arlanda? Se aktuell statistik och lär dig hur du kräver ersättning från värsta bovarna.",
    featured: true,
    color: "purple",
    date: "2026-03-07",
    readTime: "4 min"
  },
  {
    id: "arlanda-new-york-forsening-600-euro",
    title: "Arlanda till New York försenat? Få 600 € (Krav och Guide)",
    slug: "arlanda-new-york-forsening-600-euro",
    category: "Stockholm Arlanda",
    date: "2026-03-07",
    publishDate: "2026-03-07",
    readTime: "11 min",
    excerpt: "Har ditt flyg från Stockholm Arlanda (ARN) till New York (EWR/JFK) blivit försenat? Lär dig hur du säkrar 600 € ersättning enligt EU261.",
    featured: false,
    color: "blue"
  },
  {
    id: "arlanda-london-uk261-eu261-brexit",
    title: "Arlanda till London försenat? EU261 vs UK261 efter Brexit",
    slug: "arlanda-london-uk261-eu261-brexit",
    category: "Stockholm Arlanda",
    date: "2026-03-07",
    publishDate: "2026-03-07",
    readTime: "9 min",
    excerpt: "Flygproblem mellan Stockholm och London? Förstå dina rättigheter efter Brexit och lär dig hur du kräver ersättning.",
    featured: false,
    color: "blue"
  },
  {
    id: "arlanda-dubai-eu261-ersattning",
    title: "Arlanda till Dubai försenat? När gäller EU261 för Mellanösternflyg",
    slug: "arlanda-dubai-eu261-ersattning",
    category: "Stockholm Arlanda",
    date: "2026-03-07",
    publishDate: "2026-03-07",
    readTime: "10 min",
    excerpt: "Emirates eller Norwegian försenat mellan Stockholm och Dubai? Lär dig exakt när du kan kräva 600 € i ersättning enligt EU-lag.",
    featured: false,
    color: "blue"
  },
  {
    id: "arlanda-massavbokningar-kris-rattigheter",
    title: "Massavbokningar på Arlanda (ARN) — Passagerares rättigheter vid kris",
    slug: "arlanda-massavbokningar-kris-rattigheter",
    category: "Stockholm Arlanda",
    date: "2026-03-07",
    publishDate: "2026-03-07",
    readTime: "10 min",
    excerpt: "Inställda flyg i massor på Stockholm Arlanda? Lär dig dina rättigheter vid strejk, väderkaos eller IT-problem.",
    featured: false,
    color: "red"
  },
  {
    id: "malmo-airport-forsening-ersattning",
    title: "Försening eller inställt flyg på Malmö Airport (MMX) — Ersättningsguide",
    slug: "malmo-airport-forsening-ersattning",
    category: "Göteborg Landvetter",
    date: "2026-03-07",
    publishDate: "2026-03-07",
    readTime: "9 min",
    excerpt: "Fast på Malmö Sturup? Oavsett om du flyger inrikes med BRA, SAS eller Wizz Air utomlands. Se hur du kräver kompensation upp till 600 €.",
    featured: true,
    color: "green"
  },
  {
    id: "kopenhamn-kastrup-svenska-resenarer",
    title: "Köpenhamn Kastrup (CPH) som hub för svenskar — Rättigheter vid försening",
    slug: "kopenhamn-kastrup-svenska-resenarer",
    category: "Svenska Flygplatser",
    date: "2026-03-07",
    publishDate: "2026-03-07",
    readTime: "11 min",
    excerpt: "Sydsveriges främsta flygplats ligger i Danmark. Lär dig vilka regler som gäller när du flyger via CPH och missar anslutningen, eller flyget blir inställt.",
    featured: true,
    color: "red"
  },
  {
    id: "thailand-semester-forsening-ersattning",
    title: "Semesterflygningar från Sverige till Thailand — Förseningar och Ersättning",
    slug: "thailand-semester-forsening-ersattning",
    category: "Populära destinationer",
    date: "2026-03-07",
    publishDate: "2026-03-07",
    readTime: "11 min",
    excerpt: "Försenad till Asien? En guide till dina rättigheter och hur du kan kräva upp till 600 € per person vid försenade långdistansflyg.",
    featured: true,
    color: "yellow"
  },
  {
    id: "kanarieoarna-sverige-forsening-krav",
    title: "Flygningar från Sverige till Kanarieöarna — Säsongsförseningar och dina krav",
    slug: "kanarieoarna-sverige-forsening-krav",
    category: "Populära destinationer",
    date: "2026-03-07",
    publishDate: "2026-03-07",
    readTime: "10 min",
    excerpt: "Problem med semesterflyget till Gran Canaria eller Teneriffa? Läs om EU-reglerna som ger dig 400 € och hur du hanterar sandstormen (Calima).",
    featured: false,
    color: "orange"
  },
  {
    id: "spanien-grekland-sverige-flyg-problem",
    title: "Flygningar Sverige–Spanien och Grekland — Vanligaste problemen och din ersättning",
    slug: "spanien-grekland-sverige-flyg-problem",
    category: "Populära destinationer",
    date: "2026-03-07",
    publishDate: "2026-03-07",
    readTime: "10 min",
    excerpt: "Hur ATC-strejker, högtrafik och tekniska fel på sommarrutterna ger dig rätt till 400 € i kontant EU-kompensation.",
    featured: false,
    color: "blue"
  },
  {
    id: "sverige-storbritannien-uk261-eu261",
    title: "Sverige–Storbritannien — UK261 vs EU261 efter Brexit för svenska resenärer",
    slug: "sverige-storbritannien-uk261-eu261",
    category: "Populära destinationer",
    date: "2026-03-07",
    publishDate: "2026-03-07",
    readTime: "9 min",
    excerpt: "Oro för flygrättigheter efter Brexit? Lär dig hur UK261 och EU261 fungerar och säkra upp till £220 vid flygproblem.",
    featured: false,
    color: "purple"
  },
  {
    id: "transatlantiska-flyg-sverige-600-euro",
    title: "Transatlantiska flyg från Sverige — hur du kräver 600 € maximalt",
    slug: "transatlantiska-flyg-sverige-600-euro",
    category: "popular-routes",
    excerpt: "Ska du flyga till USA eller Asien? Lär dig hur du säkrar den maximala ersättningen på 600 euro vid missade byten i Europa eller USA.",
    featured: true,
    color: "blue"
  },
  {
    id: "hur-mycket-ersattning-forsenat-sas-flyg",
    title: "Hur mycket ersättning får jag för ett försenat SAS-flyg?",
    slug: "hur-mycket-ersattning-forsenat-sas-flyg",
    category: "foundation",
    excerpt: "Snabbt svar: Du kan få 250 €, 400 € eller 600 € för ett försenat SAS-flyg beroende på distans. Läs vår guide och kräv din rättmätiga flygersättning.",
    featured: true,
    color: "blue",
    date: "2026-03-07",
    readTime: "4 min"
  },
  {
    id: "hur-mycket-ersattning-installt-flyg-sverige",
    title: "Hur mycket ersättning får jag för ett inställt flyg i Sverige?",
    slug: "hur-mycket-ersattning-installt-flyg-sverige",
    category: "foundation",
    excerpt: "Få reda på exakt hur mycket pengar du har rätt till om ditt flyg från eller till Sverige ställs in.",
    featured: true,
    color: "red",
    date: "2026-03-07",
    readTime: "4 min"
  },
  {
    id: "hur-lang-tid-flygersattning-utbetald",
    title: "Hur lång tid tar det att få flygersättning utbetald?",
    slug: "hur-lang-tid-flygersattning-utbetald",
    category: "long-tail",
    excerpt: "Väntar du på dina pengar för ett försenat flyg? Så här lång tid tar det normalt att få utbetalningen.",
    featured: false,
    color: "yellow",
    date: "2026-03-07",
    readTime: "3 min"
  },
  {
    id: "krava-ersattning-flyg-3-ar-sedan",
    title: "Kan jag kräva ersättning för ett flyg för 3 år sedan?",
    slug: "krava-ersattning-flyg-3-ar-sedan",
    category: "long-tail",
    excerpt: "I Sverige och EU gäller olika preskriptionstider. Få reda på exakt hur gamla flygningar du kan kräva ersättning för.",
    featured: false,
    color: "purple",
    date: "2026-03-07",
    readTime: "3 min"
  },
  {
    id: "flygbolaget-ignorerar-min-ansokan",
    title: "Vad gör jag om flygbolaget ignorerar min ansökan?",
    slug: "flygbolaget-ignorerar-min-ansokan",
    category: "foundation",
    excerpt: "Får du inget svar från flygbolaget? Läs vår guide om nästa steg för att tvinga fram dina pengar via ombud eller ARN.",
    featured: true,
    color: "red",
    date: "2026-03-07",
    readTime: "5 min"
  },
  {
    id: "vem-far-ersattningen-resenaren-eller-researrangor",
    title: "Vem får ersättningen — resenären eller researrangören?",
    slug: "vem-far-ersattningen-resenaren-eller-researrangor",
    category: "long-tail",
    excerpt: "Betalade företaget eller resebyrån din biljett? Läs om vem som faktiskt har laglig rätt till EU-kompensationen.",
    featured: false,
    color: "blue",
    date: "2026-03-07",
    readTime: "4 min"
  },
  {
    id: "galler-eu261-flyg-utanfor-europa",
    title: "Gäller EU261 för flyg utanför Europa?",
    slug: "galler-eu261-flyg-utanfor-europa",
    category: "long-tail",
    excerpt: "Flyger du till USA eller Asien? Läs exakt när EU:s passagerarregler skyddar din utlandsresa.",
    featured: false,
    color: "green",
    date: "2026-03-07",
    readTime: "4 min"
  },
  {
    id: "behover-jag-anlita-ombud-flygersattning",
    title: "Behöver jag anlita ett ombud för att få flygersättning?",
    slug: "behover-jag-anlita-ombud-flygersattning",
    category: "foundation",
    excerpt: "Göra det själv eller ta hjälp? Vi jämför kostnader, tid och chanser att vinna mot flygbolagen.",
    featured: true,
    color: "purple",
    date: "2026-03-07",
    readTime: "4 min"
  },
  {
    id: "lonar-sig-ersattningsforetag-flygkrav",
    title: "Lönar det sig att använda ett ersättningsföretag för flygkrav?",
    slug: "lonar-sig-ersattningsforetag-flygkrav",
    category: "foundation",
    excerpt: "Läs om kostnader, chanser att vinna och varför ersättningsföretag ofta är det snabbaste sättet att få pengarna.",
    featured: true,
    color: "blue",
    date: "2026-03-07",
    readTime: "4 min"
  },
  {
    id: "hur-lang-tid-ansoka-flygersattning-sverige",
    title: "Hur lång tid har jag på mig att ansöka om flygersättning i Sverige?",
    slug: "hur-lang-tid-ansoka-flygersattning-sverige",
    category: "long-tail",
    excerpt: "Läs allt om preskriptionstiden i Sverige (och EU) för att kräva ersättning för försenade flyg. Se tidsgränserna här.",
    featured: false,
    color: "red",
    date: "2026-03-07",
    readTime: "3 min"
  },
  {
    id: "vilka-dokument-ersattning-forsenat-flyg",
    title: "Vilka dokument behöver jag för att ansöka om ersättning för försenat flyg?",
    slug: "vilka-dokument-ersattning-forsenat-flyg",
    category: "foundation",
    excerpt: "Checklista: PNR, bokningsnummer, boardingkort och kvitton. Så förbereder du din ansökan.",
    featured: false,
    color: "green",
    date: "2026-03-07",
    readTime: "4 min"
  },
  {
    id: "betalar-sas-ersattning-fakta-statistik",
    title: "Betalar SAS ersättning — fakta, statistik och bekräftade fall",
    slug: "betalar-sas-ersattning-fakta-statistik",
    category: "foundation",
    excerpt: "Statistik om SAS utbetalningar av flygersättning enligt EU261. Får du nej på ditt krav? Se hur du tvingar fram pengarna.",
    featured: true,
    color: "blue",
    date: "2026-03-07",
    readTime: "4 min"
  }
];