export type BlogArticleHiCategory =
  | "snippet"
  | "foundation"
  | "airline"
  | "airport"
  | "route"
  | "special";

export type BlogArticleHiCtaPath = "/hi/deri-udaan" | "/hi/radd-udaan";

export interface BlogArticleHi {
  id: string;
  title: string;
  slug: string;
  category: BlogArticleHiCategory;
  cluster: string;
  airportCode?: string;
  airportName?: string;
  airlineName?: string;
  routeName?: string;
  flag?: string;
  wordCount: number;
  readTime: number;
  excerpt: string;
  publishDate: string;
  featured: boolean;
  color: string;
  ctaPath: BlogArticleHiCtaPath;
}

const publishDate = "2026-04-24";

function article(
  slug: string,
  title: string,
  category: BlogArticleHiCategory,
  cluster: string,
  excerpt: string,
  options: Partial<BlogArticleHi> = {},
): BlogArticleHi {
  return {
    id: slug,
    slug,
    title,
    category,
    cluster,
    excerpt,
    publishDate,
    featured: false,
    flag: "HI",
    wordCount: 1800,
    readTime: 7,
    color: "blue",
    ctaPath: "/hi/deri-udaan",
    ...options,
  };
}

export const blogArticlesHi: BlogArticleHi[] = [
  article(
    "yurob-udaan-deri-muavza-250-400-600",
    "यूरोप में उड़ान देरी पर कितना मुआवज़ा मिलता है? €250, €400 या €600",
    "snippet",
    "त्वरित जवाब",
    "यूरोप में देरी हुई उड़ान पर €250, €400 या €600 मुआवज़ा कब मिलता है, इसे भारतीय यात्रियों के लिए रुपये में समझें।",
    { featured: true, wordCount: 2100, readTime: 8 },
  ),
  article(
    "kitne-ghante-deri-muavza-milta-hai",
    "कितने घंटे की देरी पर मुआवज़ा मिलता है?",
    "snippet",
    "त्वरित जवाब",
    "तीन घंटे की अंतिम आगमन देरी, असाधारण परिस्थितियों और EU261 पात्रता का साफ जवाब।",
    { featured: true },
  ),
  article(
    "eu261-gair-yuropeey-airline-lagu",
    "EU261 गैर-यूरोपीय एयरलाइनों पर लागू होता है?",
    "snippet",
    "त्वरित जवाब",
    "Air India, IndiGo, Emirates और Qatar जैसे गैर-यूरोपीय कैरियर पर EU261 कब लागू होता है।",
    { featured: true },
  ),
  article(
    "air-india-eu261-lagu-hota-hai-ya-nahi",
    "Air India पर EU261 लागू होता है या नहीं?",
    "snippet",
    "त्वरित जवाब",
    "Air India के लिए सबसे महत्वपूर्ण नियम: यूरोप से प्रस्थान हो तो EU261, भारत से Air India प्रस्थान हो तो सामान्यतः नहीं।",
    { featured: true, airlineName: "Air India", wordCount: 2200, readTime: 8, color: "red" },
  ),
  article(
    "airline-muavza-mana-kare-kya-karen",
    "एयरलाइन मुआवज़ा देने से मना करे तो क्या करें?",
    "snippet",
    "त्वरित जवाब",
    "एयरलाइन के इनकार, असाधारण परिस्थिति के बहाने और अगले कानूनी कदमों की व्यावहारिक गाइड।",
  ),
  article(
    "2-ghante-deri-adhikar-kya-hain",
    "2 घंटे की देरी पर क्या अधिकार हैं?",
    "snippet",
    "त्वरित जवाब",
    "दो घंटे की देरी पर देखभाल, भोजन और सहायता मिल सकती है; नकद मुआवज़ा आमतौर पर तीन घंटे की अंतिम देरी से जुड़ता है।",
  ),
  article(
    "yurob-muavze-ke-liye-kitna-samay",
    "यूरोप उड़ान मुआवज़े के लिए कितना समय है?",
    "snippet",
    "त्वरित जवाब",
    "पुरानी यूरोप उड़ानों के लिए दावा करने की समय सीमा देश के कानून पर निर्भर करती है; दस्तावेज़ जितनी जल्दी हों उतना बेहतर।",
  ),
  article(
    "3-saal-purani-udaan-muavza-mang-sakte",
    "3 साल पुरानी उड़ान के लिए मुआवज़ा मांग सकते हैं?",
    "snippet",
    "त्वरित जवाब",
    "तीन साल पुरानी उड़ान पर दावा संभव हो सकता है, लेकिन समय सीमा उस देश पर निर्भर करती है जहां दावा किया जाएगा।",
  ),
  article(
    "voucher-ki-jagah-nakad-muavza-maangein",
    "वाउचर की जगह नकद मुआवज़ा कैसे माँगें?",
    "snippet",
    "त्वरित जवाब",
    "EU261 में पात्र यात्री नकद मुआवज़ा मांग सकते हैं; एयरलाइन का वाउचर अंतिम जवाब नहीं होना चाहिए।",
  ),
  article(
    "yurob-bahar-udaan-eu261-lagu",
    "यूरोप के बाहर उड़ान पर EU261 लागू होता है?",
    "snippet",
    "त्वरित जवाब",
    "यूरोप के बाहर की उड़ानों में EU261 तभी लागू हो सकता है जब यूरोपीय एयरलाइन या यूरोप से प्रस्थान का लिंक हो।",
  ),
  article(
    "muavza-milne-mein-kitna-samay-lagta",
    "मुआवज़ा मिलने में कितना समय लगता है?",
    "snippet",
    "त्वरित जवाब",
    "साफ दस्तावेज़ और मजबूत पात्रता होने पर प्रक्रिया तेज हो सकती है; इनकार या मुकदमेबाज़ी से समय बढ़ता है।",
  ),
  article(
    "charter-udaan-eu261-lagu-hota",
    "चार्टर उड़ान पर EU261 लागू होता है?",
    "snippet",
    "त्वरित जवाब",
    "चार्टर, पैकेज टूर और सस्ती टिकट वाली यूरोपीय उड़ानें भी EU261 के दायरे में आ सकती हैं।",
  ),
  article(
    "business-class-deri-eu261-muavza",
    "बिज़नेस क्लास देरी पर भी EU261 मुआवज़ा मिलता है?",
    "snippet",
    "त्वरित जवाब",
    "मुआवज़ा टिकट कीमत या क्लास से नहीं, दूरी और देरी से तय होता है; बिज़नेस क्लास यात्री भी दावा कर सकते हैं।",
  ),
  article(
    "uk261-eu261-mein-kya-fark-hai",
    "UK261 और EU261 में क्या फ़र्क है?",
    "snippet",
    "त्वरित जवाब",
    "ब्रेक्ज़िट के बाद UK261 और EU261 अलग कानूनी ढांचे हैं, लेकिन भारतीय यात्रियों के लिए कई व्यावहारिक नियम समान रहते हैं।",
    { featured: true, color: "indigo" },
  ),
  article(
    "claimwinger-muavza-kaise-milega-no-win",
    "ClaimWinger से मुआवज़ा कैसे मिलेगा? — No win, no fee",
    "snippet",
    "त्वरित जवाब",
    "ClaimWinger के no-win-no-fee मॉडल, दस्तावेज़ जांच और एयरलाइन से दावा प्रक्रिया को सरल हिंदी में समझें।",
    { featured: true, wordCount: 2200, readTime: 8 },
  ),
  article(
    "claimwinger-vs-airhelp-bharatiy-yatri",
    "ClaimWinger vs AirHelp — भारतीय यात्रियों के लिए सबसे अच्छा विकल्प",
    "snippet",
    "त्वरित जवाब",
    "भारतीय यात्रियों के लिए ClaimWinger और AirHelp की तुलना: जोखिम, फीस, हिंदी अनुभव और यूरोप-भारत दावे।",
    { featured: true, wordCount: 2200, readTime: 8 },
  ),
  article(
    "air-india-yurob-udaan-vilamb-eu261-600",
    "Air India यूरोप उड़ान विलंब — EU261 के तहत €600 मुआवज़ा",
    "airline",
    "एयरलाइन",
    "Air India की यूरोप से भारत या भारत से यूरोप उड़ानों में EU261 कब लागू होता है और €600 तक दावा कब बनता है।",
    { featured: true, airlineName: "Air India", color: "red", wordCount: 2300, readTime: 9 },
  ),
  article(
    "air-india-muavza-asveekar-age-kya-karen",
    "Air India मुआवज़ा अस्वीकार — आगे क्या करें?",
    "airline",
    "एयरलाइन",
    "Air India के इनकार के बाद दस्तावेज़, यूरोपीय प्रस्थान, DGCA और ClaimWinger प्रक्रिया की गाइड।",
    { airlineName: "Air India", color: "red" },
  ),
  article(
    "delhi-frankfurt-vilamb-air-india-lufthansa",
    "दिल्ली–फ्रैंकफर्ट विलंब — Air India vs Lufthansa: कौन देता है मुआवज़ा?",
    "route",
    "रूट",
    "दिल्ली-फ्रैंकफर्ट रूट पर Air India और Lufthansa में EU261 पात्रता का निर्णायक फर्क।",
    { featured: true, routeName: "दिल्ली-फ्रैंकफर्ट", airlineName: "Air India / Lufthansa", color: "orange", wordCount: 2300, readTime: 9 },
  ),
  article(
    "eu261-vs-dgca-yuropeey-bharatiy-niyam-antar",
    "EU261 बनाम DGCA — यूरोपीय और भारतीय नियमों में अंतर",
    "foundation",
    "कानून और मूल बातें",
    "EU261 और DGCA के दायरे, मुआवज़े और यात्री सहायता में फर्क को भारतीय यात्रियों के नज़रिये से समझें।",
    { featured: true, color: "slate" },
  ),
  article(
    "eu261-muavza-250-400-600-kaise-tay",
    "EU261 के तहत मुआवज़ा: €250, €400 या €600 — कैसे तय होता है?",
    "foundation",
    "कानून और मूल बातें",
    "दिल्ली-लंदन, दिल्ली-फ्रैंकफर्ट और मुंबई-पेरिस जैसे रूटों पर EU261 राशि कैसे तय होती है।",
    { featured: true },
  ),
  article(
    "bharatiy-airline-eu261-antargat-air-india-indigo",
    "भारतीय एयरलाइन EU261 के अंतर्गत आती है या नहीं? — Air India, IndiGo",
    "foundation",
    "कानून और मूल बातें",
    "Air India और IndiGo जैसी भारतीय एयरलाइनों पर EU261 कब लागू होता है और कब केवल DGCA या UK261 देखना चाहिए।",
    { featured: true, airlineName: "Air India / IndiGo", color: "red" },
  ),
  article(
    "udaan-vilamb-muavza-shikayat-kaise-darz",
    "उड़ान विलंब पर मुआवज़ा — शिकायत कैसे दर्ज करें? पूरी प्रक्रिया",
    "foundation",
    "कानून और मूल बातें",
    "यूरोप उड़ान देरी पर शिकायत दर्ज करने, दस्तावेज़ जोड़ने और दावा आगे बढ़ाने की चरण-दर-चरण प्रक्रिया।",
  ),
  article(
    "yurob-udaan-vilamb-hotel-khana-parivahan",
    "यूरोप में उड़ान विलंब — होटल, खाना और परिवहन: कौन देता है?",
    "foundation",
    "कानून और मूल बातें",
    "लंबी देरी में एयरलाइन की care obligations: भोजन, होटल, परिवहन और नकद मुआवज़े का फर्क।",
  ),
  article(
    "muavze-ki-jagah-voucher-sweekar-karna",
    "मुआवज़े की जगह वाउचर — क्या आपको स्वीकार करना चाहिए?",
    "foundation",
    "कानून और मूल बातें",
    "वाउचर, नकद मुआवज़ा और भारतीय यात्रियों के लिए सुरक्षित निर्णय लेने की व्यावहारिक गाइड।",
  ),
  article(
    "indigo-yurob-udaan-eu261-kab-lagu",
    "IndiGo यूरोप उड़ान — EU261 कब लागू होता है?",
    "airline",
    "एयरलाइन",
    "IndiGo, UK261, LHR/MAN प्रस्थान और भारतीय यात्री के अधिकारों की साफ व्याख्या।",
    { airlineName: "IndiGo", color: "indigo" },
  ),
  article(
    "lufthansa-udaan-vilamb-bharatiy-yatri-eu261",
    "Lufthansa उड़ान विलंब — भारतीय यात्रियों के लिए EU261 गाइड",
    "airline",
    "एयरलाइन",
    "Lufthansa यूरोपीय कैरियर है, इसलिए भारत से यूरोप उड़ान में भी EU261 सुरक्षा बन सकती है।",
    { airlineName: "Lufthansa", featured: true },
  ),
  article(
    "swiss-airline-vilamb-delhi-zurich-adhikar",
    "Swiss एयरलाइन विलंब — दिल्ली-ज़्यूरिख़ रूट पर अधिकार",
    "airline",
    "एयरलाइन",
    "Swiss और ज़्यूरिख़ रूट पर भारतीय यात्रियों के लिए यूरोपीय शैली की यात्री सुरक्षा और दावा रणनीति।",
    { airlineName: "Swiss", routeName: "दिल्ली-ज़्यूरिख़" },
  ),
  article(
    "british-airways-vilamb-eu261-uk261-brexit",
    "British Airways उड़ान विलंब — EU261 और UK261 ब्रेक्ज़िट के बाद",
    "airline",
    "एयरलाइन",
    "British Airways, लंदन प्रस्थान और ब्रेक्ज़िट के बाद UK261 बनाम EU261 का व्यावहारिक फर्क।",
    { airlineName: "British Airways", color: "indigo" },
  ),
  article(
    "virgin-atlantic-vilamb-london-bharat-uk261",
    "Virgin Atlantic विलंब — London से भारत: UK261 के तहत अधिकार",
    "airline",
    "एयरलाइन",
    "Virgin Atlantic पर London से भारत उड़ान में UK261 कब लागू होता है और दावा कैसे बनता है।",
    { airlineName: "Virgin Atlantic", color: "pink" },
  ),
  article(
    "lot-polish-airlines-vilamb-warsaw-bharat-eu261",
    "LOT Polish Airlines विलंब — वारसॉ से भारत: EU261",
    "airline",
    "एयरलाइन",
    "LOT Polish Airlines, वारसॉ-भारत उड़ान और भारतीय यात्रियों के लिए €600 तक EU261 दावा।",
    { airlineName: "LOT Polish Airlines", routeName: "वारसॉ-भारत" },
  ),
  article(
    "ita-airways-rome-delhi-vilamb-eu261",
    "ITA Airways रोम से दिल्ली विलंब — EU261 हमेशा लागू",
    "airline",
    "एयरलाइन",
    "ITA Airways EU कैरियर है; रोम-दिल्ली विलंब में भारतीय यात्री कब €600 तक दावा कर सकते हैं।",
    { airlineName: "ITA Airways", routeName: "रोम-दिल्ली" },
  ),
  article(
    "finnair-vilamb-helsinki-bharat-eu261",
    "Finnair विलंब — हेलसिंकी से भारत EU261 गाइड",
    "airline",
    "एयरलाइन",
    "Finnair और Helsinki hub से भारत यात्रा में EU261 अधिकार, मिस्ड कनेक्शन और दस्तावेज़।",
    { airlineName: "Finnair", routeName: "हेलसिंकी-भारत" },
  ),
  article(
    "sas-vilamb-copenhagen-delhi-eu261",
    "SAS विलंब — कोपेनहेगन से दिल्ली EU261",
    "airline",
    "एयरलाइन",
    "SAS और Copenhagen-Delhi यात्रा में EU261 पात्रता और एयरलाइन जिम्मेदारी की व्याख्या।",
    { airlineName: "SAS", routeName: "कोपेनहेगन-दिल्ली" },
  ),
  article(
    "vistara-air-india-express-yurob-eu261-sthiti",
    "Vistara / Air India Express — यूरोप उड़ान: EU261 स्थिति",
    "airline",
    "एयरलाइन",
    "Vistara के Air India में विलय और Air India Express की यूरोप स्थिति को EU261 के संदर्भ में समझें।",
    { airlineName: "Vistara / Air India Express", color: "red" },
  ),
  article(
    "ryanair-vilamb-yurob-yatra-250-600-muavza",
    "Ryanair विलंब — यूरोप यात्रा के दौरान €250-€600 मुआवज़ा",
    "airline",
    "एयरलाइन",
    "यूरोप के अंदर Ryanair से यात्रा कर रहे भारतीय यात्रियों के लिए देरी और कैंसिलेशन अधिकार।",
    { airlineName: "Ryanair" },
  ),
  article(
    "easyjet-vilamb-yurob-sasti-udaan-adhikar",
    "easyJet विलंब — यूरोप में सस्ती उड़ान पर अधिकार",
    "airline",
    "एयरलाइन",
    "कम किराये वाली easyJet टिकट पर भी EU261 अधिकार और €250-€600 मुआवज़ा लागू हो सकता है।",
    { airlineName: "easyJet" },
  ),
  article(
    "wizz-air-vilamb-purvi-yurob-adhikar",
    "Wizz Air विलंब — पूर्वी यूरोप यात्रा में अधिकार",
    "airline",
    "एयरलाइन",
    "पूर्वी यूरोप में Wizz Air देरी, असाधारण परिस्थिति और भारतीय पर्यटकों के EU261 अधिकार।",
    { airlineName: "Wizz Air" },
  ),
  article(
    "air-france-vilamb-bharat-paris-eu261",
    "Air France उड़ान विलंब — भारत से पेरिस EU261 गाइड",
    "airline",
    "एयरलाइन",
    "Air France EU कैरियर है, इसलिए भारत-पेरिस रूट पर भी EU261 सुरक्षा महत्वपूर्ण हो सकती है।",
    { airlineName: "Air France", routeName: "भारत-पेरिस" },
  ),
  article(
    "mumbai-havai-adda-yurob-udaan-vilamb-eu261",
    "मुंबई हवाई अड्डे से यूरोप उड़ान विलंब — EU261 गाइड",
    "airport",
    "हवाई अड्डे",
    "मुंबई से यूरोप उड़ानों पर Lufthansa, Swiss, British Airways और Air India के लिए EU261 पात्रता।",
    { airportCode: "BOM", airportName: "मुंबई", featured: true },
  ),
  article(
    "bengaluru-havai-adda-yurob-vilamb-eu261",
    "बेंगलुरु हवाई अड्डे से यूरोप उड़ान विलंब — EU261 अधिकार",
    "airport",
    "हवाई अड्डे",
    "बेंगलुरु से यूरोप जाने वाले आईटी और बिज़नेस यात्रियों के लिए EU261 और UK261 अधिकार।",
    { airportCode: "BLR", airportName: "बेंगलुरु" },
  ),
  article(
    "chennai-havai-adda-yurob-udaan-eu261",
    "चेन्नई हवाई अड्डे से यूरोप उड़ान — EU261 गाइड",
    "airport",
    "हवाई अड्डे",
    "चेन्नई से Lufthansa, British Airways और अन्य यूरोप रूटों पर देरी का दावा कैसे समझें।",
    { airportCode: "MAA", airportName: "चेन्नई" },
  ),
  article(
    "hyderabad-havai-adda-yurob-vilamb-eu261",
    "हैदराबाद हवाई अड्डे से यूरोप उड़ान विलंब",
    "airport",
    "हवाई अड्डे",
    "हैदराबाद से यूरोप जाने वाले यात्रियों के लिए देरी, कनेक्शन और EU261 मुआवज़ा गाइड।",
    { airportCode: "HYD", airportName: "हैदराबाद" },
  ),
  article(
    "frankfurt-transit-connection-chuta-eu261",
    "फ्रैंकफर्ट हवाई अड्डे पर ट्रांज़िट — कनेक्शन छूटा: EU261",
    "airport",
    "हवाई अड्डे",
    "Frankfurt transit में missed connection होने पर एक ही बुकिंग और अंतिम आगमन देरी क्यों निर्णायक है।",
    { airportCode: "FRA", airportName: "फ्रैंकफर्ट", featured: true },
  ),
  article(
    "london-heathrow-transit-vilamb-eu261-uk261",
    "लंदन हीथ्रो पर ट्रांज़िट विलंब — EU261 या UK261?",
    "airport",
    "हवाई अड्डे",
    "Heathrow transit, UK261 और भारतीय यात्रियों के लिए लंदन कनेक्शन देरी की व्याख्या।",
    { airportCode: "LHR", airportName: "लंदन हीथ्रो", color: "indigo" },
  ),
  article(
    "paris-cdg-transit-connection-adhikar",
    "पेरिस CDG पर ट्रांज़िट — कनेक्शन छूटने पर अधिकार",
    "airport",
    "हवाई अड्डे",
    "Paris CDG में कनेक्शन छूटने पर Air France, EU261 और अंतिम गंतव्य देरी की गाइड।",
    { airportCode: "CDG", airportName: "पेरिस CDG" },
  ),
  article(
    "amsterdam-schiphol-transit-eu261-adhikar",
    "एम्स्टर्डम स्किफ़ोल — ट्रांज़िट में EU261 के तहत अधिकार",
    "airport",
    "हवाई अड्डे",
    "Schiphol transit में देरी, KLM connection और भारतीय यात्रियों के EU261 अधिकार।",
    { airportCode: "AMS", airportName: "एम्स्टर्डम स्किफ़ोल" },
  ),
  article(
    "delhi-paris-vilamb-air-india-air-france",
    "दिल्ली–पेरिस विलंब — Air India और Air France EU261",
    "route",
    "रूट",
    "दिल्ली-पेरिस रूट पर Air India और Air France के बीच EU261 पात्रता का फर्क।",
    { routeName: "दिल्ली-पेरिस", airlineName: "Air India / Air France" },
  ),
  article(
    "delhi-amsterdam-vilamb-air-india-klm",
    "दिल्ली–एम्स्टर्डम विलंब — Air India और KLM",
    "route",
    "रूट",
    "दिल्ली-एम्स्टर्डम रूट पर Air India और KLM के EU261 नियमों की तुलना।",
    { routeName: "दिल्ली-एम्स्टर्डम", airlineName: "Air India / KLM" },
  ),
  article(
    "delhi-milan-vilamb-air-india-lufthansa",
    "दिल्ली–मिलान विलंब — Air India और Lufthansa €600",
    "route",
    "रूट",
    "दिल्ली-मिलान यात्रा में Air India, Lufthansa connection और €600 तक मुआवज़े की संभावना।",
    { routeName: "दिल्ली-मिलान", airlineName: "Air India / Lufthansa" },
  ),
  article(
    "delhi-rome-vilamb-air-india-ita",
    "दिल्ली–रोम विलंब — Air India और ITA Airways",
    "route",
    "रूट",
    "दिल्ली-रोम रूट पर Air India और ITA Airways के लिए EU261 पात्रता का व्यावहारिक अंतर।",
    { routeName: "दिल्ली-रोम", airlineName: "Air India / ITA Airways" },
  ),
  article(
    "delhi-vienna-vilamb-air-india-austria",
    "दिल्ली–वियना विलंब — Air India ऑस्ट्रिया सीधी उड़ान",
    "route",
    "रूट",
    "दिल्ली-वियना उड़ान में यूरोपीय प्रस्थान, Air India और कनेक्शन देरी के नियम।",
    { routeName: "दिल्ली-वियना", airlineName: "Air India" },
  ),
  article(
    "delhi-zurich-vilamb-air-india-swiss",
    "दिल्ली–ज़्यूरिख़ विलंब — Air India और Swiss EU261",
    "route",
    "रूट",
    "दिल्ली-ज़्यूरिख़ रूट पर Swiss और Air India के दावों का फर्क और दस्तावेज़ रणनीति।",
    { routeName: "दिल्ली-ज़्यूरिख़", airlineName: "Air India / Swiss" },
  ),
  article(
    "delhi-warsaw-vilamb-lot-eu261",
    "दिल्ली–वारसॉ विलंब — LOT Polish Airlines EU261",
    "route",
    "रूट",
    "दिल्ली-वारसॉ पर LOT Polish Airlines के साथ EU261 अधिकार और €600 तक दावा।",
    { routeName: "दिल्ली-वारसॉ", airlineName: "LOT Polish Airlines" },
  ),
  article(
    "mumbai-frankfurt-vilamb-lufthansa-air-india",
    "मुंबई–फ्रैंकफर्ट विलंब — Lufthansa और Air India €600",
    "route",
    "रूट",
    "मुंबई-फ्रैंकफर्ट पर Lufthansa और Air India के EU261 नियमों की भारतीय यात्री गाइड।",
    { routeName: "मुंबई-फ्रैंकफर्ट", airlineName: "Lufthansa / Air India", featured: true },
  ),
  article(
    "mumbai-zurich-vilamb-swiss-eu261",
    "मुंबई–ज़्यूरिख़ विलंब — Swiss EU261 गाइड",
    "route",
    "रूट",
    "मुंबई-ज़्यूरिख़ पर Swiss उड़ान देरी और यूरोपीय यात्री अधिकारों की गाइड।",
    { routeName: "मुंबई-ज़्यूरिख़", airlineName: "Swiss" },
  ),
  article(
    "bengaluru-london-vilamb-ba-air-india",
    "बेंगलुरु–लंदन विलंब — British Airways और Air India",
    "route",
    "रूट",
    "बेंगलुरु-लंदन पर British Airways, Air India और UK261/EU261 पात्रता का अंतर।",
    { routeName: "बेंगलुरु-लंदन", airlineName: "British Airways / Air India", color: "indigo" },
  ),
  article(
    "delhi-copenhagen-vilamb-air-india-sas",
    "दिल्ली–कोपेनहेगन विलंब — Air India और SAS",
    "route",
    "रूट",
    "दिल्ली-कोपेनहेगन पर Air India और SAS के लिए यूरोपीय प्रस्थान और EU261 दावा।",
    { routeName: "दिल्ली-कोपेनहेगन", airlineName: "Air India / SAS" },
  ),
  article(
    "yurob-bharat-vapsi-udaan-vilamb-eu261",
    "यूरोप से भारत वापसी उड़ान विलंब — क्या EU261 लागू होता है?",
    "route",
    "रूट",
    "यूरोप से भारत लौटते समय कोई भी एयरलाइन हो, यूरोपीय हवाई अड्डे से प्रस्थान EU261 को महत्वपूर्ण बनाता है।",
    { featured: true },
  ),
  article(
    "delhi-helsinki-vilamb-finnair-eu261",
    "दिल्ली–हेलसिंकी विलंब — Finnair EU261 गाइड",
    "route",
    "रूट",
    "दिल्ली-हेलसिंकी पर Finnair उड़ान देरी, EU261 और कनेक्शन अधिकारों की गाइड।",
    { routeName: "दिल्ली-हेलसिंकी", airlineName: "Finnair" },
  ),
  article(
    "overbooking-boarding-inkar-600-muavza",
    "ओवरबुकिंग — बोर्डिंग से इनकार पर तुरंत €600 मुआवज़ा",
    "special",
    "विशेष परिस्थितियाँ",
    "ओवरबुकिंग, denied boarding और लंबी दूरी की यूरोप उड़ान पर €600 तक मुआवज़े का नियम।",
    { featured: true },
  ),
  article(
    "downgrade-business-class-economy-vapsi",
    "डाउनग्रेड — बिज़नेस क्लास खरीदकर इकोनॉमी में बैठे: वापसी कैसे?",
    "special",
    "विशेष परिस्थितियाँ",
    "बिज़नेस क्लास से इकोनॉमी में डाउनग्रेड होने पर किराये की आंशिक वापसी और दावा प्रक्रिया।",
  ),
  article(
    "mileage-ticket-eu261-muavza-milta-hai",
    "माइलेज टिकट — EU261 मुआवज़ा मिलता है या नहीं?",
    "special",
    "विशेष परिस्थितियाँ",
    "Miles & More, Flying Returns या reward ticket पर भी EU261 अधिकार कब लागू होते हैं।",
  ),
  article(
    "ota-makemytrip-booking-eu261-daava",
    "OTA से खरीदा टिकट (MakeMyTrip, Booking, Expedia) — EU261 दावा प्रभावित?",
    "special",
    "विशेष परिस्थितियाँ",
    "MakeMyTrip, Cleartrip, EaseMyTrip, Booking या Expedia से खरीदी टिकट पर EU261 दावा किससे और कैसे करें।",
    { featured: true },
  ),
  article(
    "vyapar-yatra-vilamb-company-ya-karmchari-muavza",
    "व्यापार यात्रा विलंब — कंपनी को मुआवज़ा मिलता है या कर्मचारी को?",
    "special",
    "विशेष परिस्थितियाँ",
    "बिज़नेस ट्रैवल में EU261 मुआवज़ा आमतौर पर यात्री को मिलता है, टिकट किसने खरीदा इससे हमेशा फर्क नहीं पड़ता।",
  ),
  article(
    "raat-udaan-vilamb-hotel-khana-kharcha",
    "रात में उड़ान विलंब — होटल और खाने का खर्च कौन उठाएगा?",
    "special",
    "विशेष परिस्थितियाँ",
    "रातभर देरी में होटल, भोजन, परिवहन और नकद मुआवज़े के अलग-अलग अधिकार।",
  ),
  article(
    "delhi-airport-der-se-flight",
    "दिल्ली हवाई अड्डा देर से उड़ान — मुआवज़ा और अधिकार",
    "airport",
    "मौजूदा हिंदी गाइड",
    "दिल्ली हवाई अड्डे से देरी वाली उड़ान पर भारतीय यात्रियों के अधिकार और दावा रणनीति।",
    { airportCode: "DEL", airportName: "दिल्ली", featured: true },
  ),
  article(
    "delhi-airport-cancel-flight",
    "दिल्ली हवाई अड्डा रद्द उड़ान — मुआवज़े के लिए चरण-दर-चरण गाइड",
    "airport",
    "मौजूदा हिंदी गाइड",
    "दिल्ली से रद्द उड़ान पर रिफंड, रीबुकिंग और संभावित मुआवज़े की गाइड।",
    { airportCode: "DEL", airportName: "दिल्ली", ctaPath: "/hi/radd-udaan" },
  ),
  article(
    "eu-regulation-261-2004-indian-passengers",
    "यूरोपीय संघ विनियमन EC 261/2004 — भारतीय यात्रियों के लिए संपूर्ण मार्गदर्शिका",
    "foundation",
    "मौजूदा हिंदी गाइड",
    "भारतीय यात्रियों के लिए EU261 का दायरा, राशि और दावा प्रक्रिया।",
    { featured: true },
  ),
  article(
    "flight-delay-cancellation-compensation-amount",
    "उड़ान में देरी या रद्दीकरण: मुझे कितना मुआवज़ा मिल सकता है?",
    "foundation",
    "मौजूदा हिंदी गाइड",
    "देरी या रद्द उड़ान के लिए €250, €400 या €600 मुआवज़ा कब मिलता है।",
    { featured: true },
  ),
  article(
    "delhi-london-flight-cancelled-compensation",
    "दिल्ली-लंदन उड़ान रद्द — मुआवज़े के लिए कदम दर कदम प्रक्रिया",
    "route",
    "मौजूदा हिंदी गाइड",
    "दिल्ली-लंदन रूट पर Air India, British Airways और UK261/EU261 संदर्भ।",
    { routeName: "दिल्ली-लंदन", ctaPath: "/hi/radd-udaan" },
  ),
  article(
    "mumbai-frankfurt-flight-delay-compensation",
    "मुंबई-फ्रैंकफर्ट उड़ान में देरी — यूरोपीय कानून के तहत आपके अधिकार",
    "route",
    "मौजूदा हिंदी गाइड",
    "मुंबई-फ्रैंकफर्ट रूट पर Lufthansa, Air India और EU261 दावा।",
    { routeName: "मुंबई-फ्रैंकफर्ट" },
  ),
  article(
    "emirates-qatar-etihad-europe-via-gulf-hubs",
    "Emirates, Qatar Airways और Etihad के माध्यम से यूरोप — खाड़ी हब पर अधिकार",
    "airline",
    "मौजूदा हिंदी गाइड",
    "दुबई, दोहा या अबू धाबी कनेक्शन से यूरोप जाते समय EU261 कब लागू होता है।",
    { airlineName: "Emirates / Qatar / Etihad" },
  ),
  article(
    "extraordinary-circumstances-compensation",
    "असाधारण परिस्थितियाँ — कब एयरलाइन पैसे देने से मना कर सकती है?",
    "foundation",
    "मौजूदा हिंदी गाइड",
    "तकनीकी खराबी, खराब मौसम, ATC और स्ट्राइक में एयरलाइन की जिम्मेदारी कैसे समझें।",
  ),
  article(
    "turkish-airlines-istanbul-compensation-rights",
    "Turkish Airlines और इस्तांबुल हब — क्या EU कानून लागू होता है?",
    "airline",
    "मौजूदा हिंदी गाइड",
    "Turkish Airlines, Istanbul transit और EU261 लागू होने की सीमाएं।",
    { airlineName: "Turkish Airlines" },
  ),
  article(
    "klm-air-france-amsterdam-paris-compensation",
    "KLM और Air France — एम्स्टर्डम और पेरिस के माध्यम से यात्रा",
    "airline",
    "मौजूदा हिंदी गाइड",
    "KLM और Air France EU कैरियर हैं, इसलिए भारत से उड़ान पर भी EU261 मजबूत हो सकता है।",
    { airlineName: "KLM / Air France", featured: true },
  ),
  article(
    "lufthansa-british-airways-air-france-comparison",
    "Lufthansa, British Airways और Air France — भारतीय यात्रियों के लिए तुलना",
    "airline",
    "मौजूदा हिंदी गाइड",
    "तीन बड़े यूरोपीय/UK कैरियर में देरी, UK261 और EU261 के फर्क की तुलना।",
    { airlineName: "Lufthansa / British Airways / Air France" },
  ),
  article(
    "air-india-international-delay-complaint",
    "Air India अंतरराष्ट्रीय उड़ान में देरी — शिकायत और मुआवज़ा प्रक्रिया",
    "airline",
    "मौजूदा हिंदी गाइड",
    "Air India अंतरराष्ट्रीय देरी में DGCA, EU261 और यूरोप प्रस्थान का फर्क।",
    { airlineName: "Air India", featured: true, color: "red" },
  ),
  article(
    "dgca-vs-eu261-compensation-comparison",
    "DGCA बनाम EU261 — भारतीय यात्रियों के लिए मुआवज़ा तुलना",
    "foundation",
    "मौजूदा हिंदी गाइड",
    "भारत के DGCA नियम और यूरोप के EU261 नियमों की व्यावहारिक तुलना।",
  ),
];

export const getCategoryLabelHi = (category: BlogArticleHiCategory): string => {
  const labels: Record<BlogArticleHiCategory, string> = {
    snippet: "त्वरित उत्तर",
    foundation: "कानून और मूल बातें",
    airline: "एयरलाइन",
    airport: "हवाई अड्डा",
    route: "रूट",
    special: "विशेष स्थिति",
  };

  return labels[category];
};

export const getArticlesByCategoryHi = (category: BlogArticleHiCategory): BlogArticleHi[] => {
  return blogArticlesHi.filter((article) => article.category === category);
};

export const getFeaturedArticlesHi = (): BlogArticleHi[] => {
  return blogArticlesHi.filter((article) => article.featured);
};

export const getTotalWordCountHi = (): number => {
  return blogArticlesHi.reduce((total, article) => total + article.wordCount, 0);
};
