import type { BlogArticleEnIreland } from "@/lib/blogArticlesEnIreland";

export type EnIrelandArticleEditorialProfile = {
  scenario: string;
  decisionPoint: string;
  evidenceFocus: string;
  faqQuestion: string;
  faqAnswer: string;
};

const defaultProfile: EnIrelandArticleEditorialProfile = {
  scenario:
    "Treat the itinerary as a timeline: booking, check-in, gate information, actual departure, final arrival and the airline's written explanation.",
  decisionPoint:
    "The decisive question is not only how long you waited at the airport, but whether the covered journey arrived late enough for EU261 or UK261 compensation.",
  evidenceFocus:
    "Keep the booking reference, boarding pass, airline emails, app screenshots and proof of final arrival time before you contact the airline.",
  faqQuestion: "What detail changes the result most?",
  faqAnswer:
    "The most important detail is usually the combination of departure airport, operating carrier, final arrival delay and the airline's reason. A small change in direction or carrier can move the case from covered to not covered.",
};

export const enIrelandArticleProfiles: Record<string, EnIrelandArticleEditorialProfile> = {
  "eu261-passenger-rights-irish-travellers": {
    scenario: "An Irish traveller comparing Dublin, Cork, Shannon, Knock and Belfast needs one map of rights before choosing the claim route.",
    decisionPoint: "First identify whether the journey is an Irish airport departure, an EU carrier arrival, or a UK airport departure; the legal framework follows that geography.",
    evidenceFocus: "Build a clean timeline with scheduled and actual arrival, the operating carrier, the disruption reason and any care costs paid during the wait.",
    faqQuestion: "Why is an Ireland-specific EU261 guide useful?",
    faqAnswer: "Ireland combines EU261 departures, UK261 border-region travel, long-haul US routes and a six-year limitation period. A generic EU261 article often misses those Irish details.",
  },
  "eu261-flights-outside-eu-ireland": {
    scenario: "A Dublin-Dubai, Dublin-New York or Dublin-Istanbul passenger may assume the non-European destination removes EU261, but the Irish departure can still be decisive.",
    decisionPoint: "Check the direction first: leaving Ireland is usually stronger than returning to Ireland on a non-EU airline.",
    evidenceFocus: "Keep both outbound and return boarding passes because the same airline can have a different result on each leg.",
    faqQuestion: "Does the destination being outside Europe block the claim?",
    faqAnswer: "No. A flight departing from Ireland can still be covered by EU261 even if it lands outside Europe. The return leg depends heavily on the operating carrier.",
  },
  "extraordinary-circumstances-ireland-airlines": {
    scenario: "Irish passengers often receive a short refusal saying 'operational reasons' or 'air traffic control', without enough detail to test the defence.",
    decisionPoint: "Ask whether the event was genuinely outside the airline's control and whether the airline took reasonable measures to reduce the delay.",
    evidenceFocus: "Save the exact refusal wording, airport notices, weather information, crew-change messages and any later explanation from the airline.",
    faqQuestion: "Is a technical fault automatically extraordinary?",
    faqAnswer: "Usually no. Many technical faults are treated as part of normal airline operations unless the airline can prove a truly external or unusual cause.",
  },
  "iaa-complaints-ireland-aviation-regulator": {
    scenario: "A passenger who has already complained to the airline may need an Irish enforcement path when the reply is late, vague or plainly wrong.",
    decisionPoint: "Use the IAA route after giving the airline a fair chance to respond and after collecting the documents needed to explain the case clearly.",
    evidenceFocus: "Keep the original claim, airline response, booking confirmation, boarding pass, flight status proof and a short chronology for the IAA.",
    faqQuestion: "Should I contact the IAA before the airline?",
    faqAnswer: "Usually no. Start with the airline so there is a record of the claim and response. The IAA route is strongest when you can show what the airline did or did not answer.",
  },
  "ccpc-ireland-consumer-rights-air-passengers": {
    scenario: "Some Irish flight disputes are not only EU261 questions: refunds, misleading voucher wording and booking platform issues may also raise consumer concerns.",
    decisionPoint: "Separate the statutory compensation claim from broader consumer issues such as unclear sales pages, refund handling or payment disputes.",
    evidenceFocus: "Keep screenshots of the sales flow, fare conditions, payment confirmation, refund requests and airline or agent messages.",
    faqQuestion: "When does the CCPC angle matter?",
    faqAnswer: "It matters most when the problem goes beyond arrival delay compensation and involves consumer information, refunds, vouchers or trader behaviour.",
  },
  "eu261-claim-limitation-period-ireland": {
    scenario: "An old Ryanair, Aer Lingus or transatlantic disruption from several years ago may still be worth checking because Ireland's period is unusually long.",
    decisionPoint: "Do not discard a case only because it is three or four years old; check whether the Irish six-year period can still apply.",
    evidenceFocus: "Recover old booking emails, payment records, calendar entries, airline app screenshots and passport travel stamps where useful.",
    faqQuestion: "Can a very old Irish flight still be claimable?",
    faqAnswer: "Often yes, if it is still within Ireland's limitation period and the evidence can be reconstructed. Older claims need especially clear documents.",
  },
  "compensation-vs-refund-ireland-eu261": {
    scenario: "A cancelled Irish flight can create several rights at once: refund, rerouting, care and sometimes fixed compensation.",
    decisionPoint: "Do not let a refund discussion erase a separate EUR250, EUR400 or EUR600 compensation question.",
    evidenceFocus: "Keep proof of the cancellation notice time, refund or rerouting offer, alternative flights and any care expenses.",
    faqQuestion: "Can I get both a refund and compensation?",
    faqAnswer: "Sometimes yes. A refund or rerouting right is separate from fixed compensation, though the exact result depends on cancellation timing and the airline's reason.",
  },
  "us-pre-clearance-dublin-eu261-applies": {
    scenario: "A US-bound passenger may clear immigration in Dublin and then face a delay after pre-clearance, which creates confusion about jurisdiction.",
    decisionPoint: "Pre-clearance does not move the departure airport out of Ireland; the flight still needs to be assessed as leaving Dublin.",
    evidenceFocus: "Keep the boarding pass, gate notices, pre-clearance timing if available, and proof of arrival time in the United States.",
    faqQuestion: "Does US pre-clearance turn the flight into a US domestic issue?",
    faqAnswer: "No. Pre-clearance changes immigration processing, not the fact that the aircraft departs from Ireland for EU261 purposes.",
  },
  "ryanair-delayed-flight-eu261-ireland": {
    scenario: "Ryanair's home-market passengers often fly short routes where EUR250 is the main band, but the three-hour arrival threshold still controls the claim.",
    decisionPoint: "Check the final arrival time, not the departure delay shown on airport boards or the Ryanair app.",
    evidenceFocus: "Save the Ryanair app timeline, gate delay screenshots, actual landing or door-opening evidence and any message naming the disruption reason.",
    faqQuestion: "Does EU261 apply to Ryanair in Ireland?",
    faqAnswer: "Yes. Ryanair is an EU carrier and Irish airport departures are covered, but compensation still depends on delay length and the airline's defence.",
  },
  "ryanair-cancelled-flight-ireland-rights": {
    scenario: "A Ryanair cancellation can leave passengers choosing between a refund, rerouting, later travel and a separate compensation claim.",
    decisionPoint: "The notice period is central: cancellations within 14 days deserve closer compensation review.",
    evidenceFocus: "Keep the cancellation email timestamp, rerouting options shown by Ryanair, the replacement flight and any extra transport or hotel receipts.",
    faqQuestion: "Is a Ryanair refund the end of the case?",
    faqAnswer: "Not always. Refund and rerouting rights are separate from possible compensation if the cancellation timing and reason qualify.",
  },
  "ryanair-rejected-claim-ireland-force-payment": {
    scenario: "A Ryanair refusal often turns on a broad extraordinary-circumstances statement that needs to be tested against the route and timeline.",
    decisionPoint: "A rejection is not the final legal answer; the airline should identify the specific event and why it could not avoid the disruption.",
    evidenceFocus: "Keep the rejection text, original claim, flight status records and any contradictory airport or tracker evidence.",
    faqQuestion: "What should I do after Ryanair rejects a claim?",
    faqAnswer: "Ask for the specific reason, compare it with the evidence and consider escalation through the Irish routes or a no-win, no-fee claim service.",
  },
  "ryanair-voucher-cash-ireland-demand": {
    scenario: "A passenger may be offered credit because it is easier for the airline, even when statutory cash compensation is the real issue.",
    decisionPoint: "Separate voluntary commercial credit from EU261 cash compensation and avoid clicking acceptance language you do not understand.",
    evidenceFocus: "Save the voucher offer, terms, expiry date, any acceptance screen and your written request for cash.",
    faqQuestion: "Can Ryanair force me to take a voucher?",
    faqAnswer: "If EU261 gives you a cash compensation right, a voucher should not replace it unless you knowingly agree. Keep the wording before responding.",
  },
  "aer-lingus-delayed-flight-eu261-compensation": {
    scenario: "Aer Lingus delay cases often involve Dublin hub flights, UK connections or long-haul services where the compensation band can change quickly.",
    decisionPoint: "Identify whether the itinerary is short-haul, European medium-haul or transatlantic before estimating the amount.",
    evidenceFocus: "Keep Aer Lingus emails, Aer Club booking details, boarding pass, final arrival proof and any explanation at the gate.",
    faqQuestion: "Does Aer Lingus always fall under EU261?",
    faqAnswer: "Aer Lingus is an EU carrier, so EU261 is usually strong for Irish departures and many arrivals into Ireland. The case still needs the delay and cause checks.",
  },
  "aer-lingus-cancelled-flight-refund-rebook": {
    scenario: "When Aer Lingus cancels, passengers often focus on the replacement flight and forget to preserve the original notice time.",
    decisionPoint: "The cancellation notice window and the arrival time of any rerouting decide whether compensation remains possible.",
    evidenceFocus: "Save the first cancellation message, rebooking options, final chosen itinerary and arrival time on the replacement flight.",
    faqQuestion: "Does rebooking remove an Aer Lingus compensation claim?",
    faqAnswer: "No, not automatically. Rerouting can reduce or remove compensation in some cases, but the timing and final arrival still need checking.",
  },
  "aer-lingus-transatlantic-delayed-600": {
    scenario: "Aer Lingus long-haul routes from Dublin and Shannon often sit in the EUR600 band, especially for US services.",
    decisionPoint: "Focus on final arrival in the US or Ireland and whether the airline can prove an extraordinary circumstance.",
    evidenceFocus: "Keep pre-clearance records where relevant, boarding pass, final arrival evidence and Aer Lingus messages about aircraft or crew issues.",
    faqQuestion: "Why are Aer Lingus transatlantic claims high value?",
    faqAnswer: "Most transatlantic routes exceed 3,500 km, so EUR600 can be in play when the covered flight reaches the legal delay threshold.",
  },
  "aer-lingus-rejected-claim-what-to-do": {
    scenario: "An Aer Lingus rejection may be legally weak if it relies on a general phrase without explaining the event and mitigation steps.",
    decisionPoint: "Compare the rejection against EU261 rules and ask whether the airline has proved the defence, not merely asserted it.",
    evidenceFocus: "Keep the rejection, any operational reason, screenshots of flight movement, and your written follow-up asking for detail.",
    faqQuestion: "Should I reply to an Aer Lingus refusal?",
    faqAnswer: "Yes, if the refusal is vague. Ask for the specific cause and keep the exchange because it can help later escalation.",
  },
  "aer-lingus-technical-fault-extraordinary": {
    scenario: "A gate announcement about a technical issue can sound final, but many technical problems are normal airline operational risks.",
    decisionPoint: "Ask whether the fault was inherent in normal aircraft operation or caused by a genuinely external event.",
    evidenceFocus: "Record the exact wording of gate announcements, maintenance-delay messages and any later explanation from Aer Lingus.",
    faqQuestion: "Does a technical fault always defeat EU261?",
    faqAnswer: "No. Routine technical faults often do not qualify as extraordinary circumstances, though rare external defects can be different.",
  },
  "british-airways-dublin-delay-eu261-uk261": {
    scenario: "Dublin-London passengers cross a legal border as well as a route border: the framework changes with direction after Brexit.",
    decisionPoint: "From Dublin, EU261 is the starting point; from Heathrow or another UK airport, UK261 is usually the correct route.",
    evidenceFocus: "Keep both legs separately documented because the outbound and return may need different legal labels.",
    faqQuestion: "Is British Airways Dublin-London EU261 or UK261?",
    faqAnswer: "Dublin departures are generally EU261. UK departures are generally UK261 after Brexit, even if the passenger lives in Ireland.",
  },
  "easyjet-delay-ireland-eu261-2026": {
    scenario: "easyJet passengers from Ireland may book low fares, but ticket price does not reduce statutory compensation.",
    decisionPoint: "A low-cost fare still needs the same EU261 test: covered route, qualifying delay and no proven extraordinary circumstance.",
    evidenceFocus: "Keep the easyJet booking reference, app notifications, boarding pass and arrival-time proof.",
    faqQuestion: "Does a cheap easyJet fare reduce compensation?",
    faqAnswer: "No. EU261 compensation is fixed by distance and eligibility, not by how much the ticket cost.",
  },
  "wizz-air-delay-dublin-eu261-wizz-credit": {
    scenario: "Wizz Air passengers may see credit or account-based remedies, but EU261 compensation is a cash-rights question.",
    decisionPoint: "Check whether the offer is a voluntary credit, refund, care reimbursement or statutory compensation.",
    evidenceFocus: "Save the Wizz account notice, credit offer terms, delay messages and proof of final arrival time.",
    faqQuestion: "Is Wizz credit the same as EU261 compensation?",
    faqAnswer: "No. Credit can be useful, but it should not be confused with statutory cash compensation when EU261 applies.",
  },
  "lufthansa-delay-ireland-eu261-always": {
    scenario: "Lufthansa cases often involve Dublin-Frankfurt or Dublin-Munich connections where the onward missed flight matters more than the first delay.",
    decisionPoint: "If the booking is one itinerary, measure the delay at the final destination, not only at the German hub.",
    evidenceFocus: "Keep the full Lufthansa itinerary, connection details, boarding passes for all legs and rebooking records.",
    faqQuestion: "Can a short Lufthansa delay still create a claim?",
    faqAnswer: "Yes, if it causes a missed connection on one booking and the final arrival delay reaches the legal threshold.",
  },
  "klm-delay-dublin-amsterdam-eu261": {
    scenario: "KLM's Amsterdam hub creates many one-booking connection cases for Irish passengers travelling beyond the Netherlands.",
    decisionPoint: "The Amsterdam arrival delay is less important than the final arrival delay if the onward flight was on the same booking.",
    evidenceFocus: "Keep the full KLM itinerary, missed-connection notice, replacement boarding pass and final arrival evidence.",
    faqQuestion: "Does Amsterdam hub disruption count for the final destination?",
    faqAnswer: "It can, if the journey was on one booking. EU261 usually looks at arrival at the final destination in that protected itinerary.",
  },
  "air-france-delay-ireland-eu261": {
    scenario: "Air France claims often turn on Paris CDG connections, where a delay from Ireland can break the onward itinerary.",
    decisionPoint: "Check whether the Paris connection was protected on a single booking and how late the final destination was reached.",
    evidenceFocus: "Keep CDG connection evidence, rebooking messages, boarding passes and the final arrival timestamp.",
    faqQuestion: "Does a missed CDG connection help the claim?",
    faqAnswer: "Yes, if the itinerary was one booking and the final destination delay reaches the EU261 threshold.",
  },
  "emirates-delay-dublin-eu261-applies": {
    scenario: "Emirates Dublin-Dubai is a classic direction-sensitive case: the Irish departure is strong, the Dubai return is much weaker under EU261.",
    decisionPoint: "Do not use the same answer for both directions; Dublin departure and Dubai departure must be analysed separately.",
    evidenceFocus: "Keep separate proof for the Dublin-Dubai leg and the Dubai-Dublin leg, including operating carrier and actual arrival.",
    faqQuestion: "Does EU261 apply to Emirates from Dublin?",
    faqAnswer: "Yes, for a covered flight departing Dublin. A return from Dubai on Emirates is usually outside EU261 because Emirates is not an EU carrier.",
  },
  "turkish-airlines-delay-dublin-eu261": {
    scenario: "Turkish Airlines passengers may connect in Istanbul, but EU261 strength depends heavily on whether the disrupted leg started in Dublin.",
    decisionPoint: "Dublin departure can be covered; Istanbul departure on Turkish usually needs a different analysis outside EU261.",
    evidenceFocus: "Keep the one-booking itinerary, Istanbul connection details, replacement flights and final arrival proof.",
    faqQuestion: "Is Turkish Airlines covered from Dublin?",
    faqAnswer: "A Turkish Airlines flight departing Dublin can be covered by EU261. The return from Istanbul on Turkish is usually not covered by EU261.",
  },
  "american-airlines-delay-dublin-eu261": {
    scenario: "American Airlines from Dublin is covered differently from American Airlines returning from the United States.",
    decisionPoint: "A Dublin departure can trigger EU261 even on American; a US departure on American usually cannot.",
    evidenceFocus: "Keep Dublin pre-clearance details, boarding pass, American Airlines messages and final arrival proof in the US.",
    faqQuestion: "Does EU261 apply to American Airlines from Dublin?",
    faqAnswer: "Yes, on flights departing Dublin. It usually does not apply to the return from the US on American because the carrier is non-EU.",
  },
  "united-airlines-delay-dublin-eu261": {
    scenario: "United flights from Dublin to US hubs can be high-value claims, but the return direction often falls outside EU261.",
    decisionPoint: "Confirm whether the disrupted United flight departed from Dublin or from a US airport.",
    evidenceFocus: "Keep United app notices, pre-clearance timing where relevant, boarding pass and arrival evidence at the US hub.",
    faqQuestion: "Can United owe EU261 compensation from Dublin?",
    faqAnswer: "Yes, if the flight departs Dublin and meets the delay or cancellation threshold. A US-origin United flight is usually different.",
  },
  "delta-airlines-delay-dublin-eu261": {
    scenario: "Delta passengers from Dublin may be protected on the outbound even though Delta is a non-EU airline.",
    decisionPoint: "The decisive fact is the Irish departure, not Delta's US ownership, for the Dublin outbound leg.",
    evidenceFocus: "Keep Delta communications, gate-delay proof, pre-clearance context and final arrival timestamp.",
    faqQuestion: "Does Delta being American remove EU261 from Dublin?",
    faqAnswer: "No. A non-EU airline can still be covered when the flight departs from an Irish airport.",
  },
  "norwegian-delay-dublin-eu261": {
    scenario: "Norwegian-style low-cost itineraries can involve separate tickets, which changes missed-connection risk for Irish passengers.",
    decisionPoint: "Check whether the onward flight was on the same booking or a self-transfer bought separately.",
    evidenceFocus: "Keep proof of ticket structure, booking references and whether the airline sold the journey as one itinerary.",
    faqQuestion: "Does a separate-ticket connection count?",
    faqAnswer: "Usually it is harder. EU261 missed-connection protection is strongest when the journey is on one booking.",
  },
  "sunexpress-delay-cork-eu261": {
    scenario: "Cork leisure flights can feel informal or seasonal, but EU261 still applies to covered departures and EU carriers.",
    decisionPoint: "Confirm the operating carrier and whether the disruption was on the Cork departure or a return leg.",
    evidenceFocus: "Keep package-holiday documents, Cork boarding pass, airline notice and any hotel or transfer receipts.",
    faqQuestion: "Are leisure routes from Cork covered?",
    faqAnswer: "They can be. EU261 does not disappear because the flight is seasonal, leisure-focused or part of a package holiday.",
  },
  "dublin-airport-delayed-flight-eu261": {
    scenario: "Dublin Airport delays can involve short European hops, UK routes and long-haul US services, so the airport alone is not enough.",
    decisionPoint: "Start with the operating carrier, destination and final arrival delay before estimating EUR250, EUR400 or EUR600.",
    evidenceFocus: "Keep DUB gate screenshots, airline messages, boarding pass and proof of when the aircraft reached the final destination.",
    faqQuestion: "Does every Dublin Airport delay qualify?",
    faqAnswer: "No. Dublin departure helps establish EU261 coverage, but compensation still needs the time threshold and no valid airline defence.",
  },
  "dublin-airport-cancelled-flight-rights": {
    scenario: "A Dublin cancellation can create immediate practical needs and a later compensation question.",
    decisionPoint: "Record when you were told about the cancellation and what rerouting or refund options were offered.",
    evidenceFocus: "Save the cancellation notice, replacement itinerary, refund request, meal or hotel receipts and final arrival details.",
    faqQuestion: "What matters most after a Dublin cancellation?",
    faqAnswer: "The cancellation notice time, airline reason and rerouting outcome usually decide whether compensation is possible alongside refund or care rights.",
  },
  "cork-airport-delayed-flight-eu261": {
    scenario: "Cork Airport passengers often have fewer alternative flights, so care and rerouting evidence can be especially important.",
    decisionPoint: "Check both compensation and practical care rights if the delay created meals, hotel or transport costs.",
    evidenceFocus: "Keep Cork Airport receipts, airline notices, boarding pass and proof of any rerouting offered from Dublin or another airport.",
    faqQuestion: "Does Cork being a smaller airport weaken EU261?",
    faqAnswer: "No. Cork is an Irish airport, so covered departures are assessed under the same EU261 principles as Dublin.",
  },
  "cork-airport-cancelled-flight-compensation": {
    scenario: "When a Cork flight is cancelled, passengers may be pushed toward a Dublin alternative, bus transfer or next-day reroute.",
    decisionPoint: "Check whether the alternative arrived close enough to the original schedule and whether the cancellation was within 14 days.",
    evidenceFocus: "Keep cancellation notice, transfer details, reroute arrival time and receipts for meals, hotel or ground transport.",
    faqQuestion: "Can a Cork cancellation still lead to compensation if I was rerouted?",
    faqAnswer: "Yes, depending on notice, reason and final arrival time. Rerouting does not automatically erase the compensation question.",
  },
  "shannon-airport-delayed-flight-eu261": {
    scenario: "Shannon is especially important for transatlantic passengers because long-haul distance and US pre-clearance often meet in one claim.",
    decisionPoint: "Separate the pre-clearance process from the flight's actual departure and final arrival delay.",
    evidenceFocus: "Keep Shannon boarding pass, pre-clearance context, airline notices and arrival-time proof in the US or Ireland.",
    faqQuestion: "Why are Shannon claims often valuable?",
    faqAnswer: "Many Shannon cases involve long-haul routes, so EUR600 can be relevant when the legal threshold is met.",
  },
  "shannon-airport-transatlantic-delay-600": {
    scenario: "A Shannon transatlantic delay can put EUR600 per passenger in play, but only if the flight is covered and the airline lacks a defence.",
    decisionPoint: "Measure the arrival delay at the transatlantic destination and identify whether the operating carrier changes the return-leg result.",
    evidenceFocus: "Keep SNN departure proof, carrier messages, pre-clearance details and final arrival records.",
    faqQuestion: "Is Shannon-New York automatically EUR600?",
    faqAnswer: "No. The distance band may be EUR600, but eligibility still depends on delay, cause and EU261 coverage.",
  },
  "ireland-west-airport-knock-delayed-eu261": {
    scenario: "Knock passengers may have limited replacement options, which makes care rights and clear airline communication particularly valuable.",
    decisionPoint: "Check whether the delayed flight departed from Knock and whether final arrival crossed the compensation threshold.",
    evidenceFocus: "Keep Knock boarding pass, airport delay notices, receipts caused by the wait and the airline's stated reason.",
    faqQuestion: "Does EU261 apply from Knock Airport?",
    faqAnswer: "Yes, qualifying departures from Ireland West Airport Knock can be covered. The usual delay and cause tests still apply.",
  },
  "belfast-international-airport-eu261-uk261": {
    scenario: "Border-region passengers may live in Ireland but depart from Belfast, which usually changes the claim from EU261 to UK261.",
    decisionPoint: "Use the airport of departure, not the passenger's home address, to choose the legal framework.",
    evidenceFocus: "Keep BFS boarding pass, UK departure proof, airline messages and any return-leg Irish documents separately.",
    faqQuestion: "Does living in Ireland make Belfast flights EU261?",
    faqAnswer: "No. Belfast is a UK airport, so UK261 is usually the starting point after Brexit.",
  },
  "dublin-airport-missed-connection-compensation": {
    scenario: "A missed connection at Dublin can be protected on one booking but risky on separate self-transfer tickets.",
    decisionPoint: "Find out whether the airline sold the itinerary as a single booking through to the final destination.",
    evidenceFocus: "Keep all booking references, missed-connection notices, replacement boarding passes and final arrival time.",
    faqQuestion: "Does Dublin missed-connection compensation require one booking?",
    faqAnswer: "It is strongest on one booking. Separate tickets can leave the passenger responsible for the onward connection.",
  },
  "long-delay-dublin-airport-hotel-meals": {
    scenario: "A long Dublin Airport delay may trigger meals, hotel and transport support before the fixed compensation question is resolved.",
    decisionPoint: "Separate care rights during the wait from the later EUR250, EUR400 or EUR600 compensation assessment.",
    evidenceFocus: "Keep meal, hotel and taxi receipts, airline care offers, delay messages and final arrival proof.",
    faqQuestion: "Can I claim hotel costs even if compensation is disputed?",
    faqAnswer: "Potentially yes. Care rights are separate from fixed compensation and can apply during long waits even where the airline disputes the cause.",
  },
  "dublin-new-york-jfk-delayed-eu261-600": {
    scenario: "Dublin-JFK passengers may fly Aer Lingus or a US carrier, but the Dublin departure keeps EU261 central on the outbound.",
    decisionPoint: "Check the operating carrier and direction: Dublin-JFK is stronger under EU261 than JFK-Dublin on a US carrier.",
    evidenceFocus: "Keep DUB pre-clearance context, JFK arrival time, carrier notices and boarding pass.",
    faqQuestion: "Is Dublin-JFK a EUR600 route?",
    faqAnswer: "It normally falls in the long-haul distance band, so EUR600 can be in play if the flight qualifies.",
  },
  "dublin-boston-delayed-eu261-600": {
    scenario: "Dublin-Boston combines heavy Irish-American travel with a long-haul compensation band.",
    decisionPoint: "The outbound from Dublin can be EU261 even on a US carrier, while the Boston return depends on the carrier.",
    evidenceFocus: "Keep proof of departure from Dublin, Boston arrival delay and any airline explanation tied to aircraft, crew or weather.",
    faqQuestion: "Does Irish-American diaspora travel change the legal test?",
    faqAnswer: "No. It explains why the route matters commercially, but the legal test remains coverage, delay and cause.",
  },
  "dublin-chicago-delayed-eu261-600": {
    scenario: "Dublin-Chicago passengers often connect onward in the US, making final-destination evidence important.",
    decisionPoint: "If the US onward leg is on the same booking, check whether the final destination delay increases the claim value.",
    evidenceFocus: "Keep O'Hare connection records, rebooking details, boarding passes and final arrival proof.",
    faqQuestion: "Does a missed US connection after Chicago matter?",
    faqAnswer: "It can matter if the onward leg was part of the same booking and the covered disruption caused a late final arrival.",
  },
  "dublin-los-angeles-delayed-eu261-600": {
    scenario: "Dublin-Los Angeles is a long route where even a single family booking can create a large total claim.",
    decisionPoint: "Confirm the delay at LAX and whether the airline has a valid extraordinary-circumstances defence.",
    evidenceFocus: "Keep LAX arrival proof, Aer Lingus messages if applicable, pre-clearance context and all passenger boarding passes.",
    faqQuestion: "Why is Dublin-LAX high value?",
    faqAnswer: "The distance usually puts the route in the EUR600 band per passenger when EU261 applies and the legal threshold is met.",
  },
  "dublin-san-francisco-delayed-eu261": {
    scenario: "Dublin-San Francisco often serves business and tech travel, where arrival time can be well documented through meetings and transfers.",
    decisionPoint: "Use objective final arrival evidence rather than relying only on the airline's delay summary.",
    evidenceFocus: "Keep SFO arrival proof, meeting disruption records if useful, airline notices and boarding passes.",
    faqQuestion: "Do business consequences increase EU261 compensation?",
    faqAnswer: "No. EU261 amounts are fixed, but business records can help prove the timing and seriousness of the disruption.",
  },
  "dublin-miami-delayed-eu261-600": {
    scenario: "Dublin-Miami leisure passengers may have cruise, hotel or onward plans that make documentation of arrival time easy to preserve.",
    decisionPoint: "The claim amount is not based on holiday cost; it is based on EU261 distance and eligibility.",
    evidenceFocus: "Keep airline notices, Miami arrival proof, cruise or hotel timing documents and receipts for care expenses.",
    faqQuestion: "Does an expensive holiday increase the EUR600 amount?",
    faqAnswer: "No. Fixed compensation remains statutory, but extra receipts may matter for separate care or reimbursement issues.",
  },
  "dublin-toronto-delayed-eu261-appr": {
    scenario: "Dublin-Toronto creates a useful comparison: EU261 may govern the Dublin outbound, while Canadian APPR may be relevant on return.",
    decisionPoint: "Choose the framework by direction and carrier instead of mixing EU and Canadian rules into one claim.",
    evidenceFocus: "Keep outbound and return documents separately, including carrier, airport of departure and final arrival proof.",
    faqQuestion: "Can EU261 and Canadian APPR both matter?",
    faqAnswer: "They can matter on different legs. Dublin departure may be EU261, while Canada departure may need APPR analysis.",
  },
  "dublin-washington-dc-delayed-eu261": {
    scenario: "Dublin-Washington passengers often travel for government, business or family reasons, but the legal amount still follows distance.",
    decisionPoint: "Confirm whether the flight departed Dublin and whether arrival at IAD crossed the three-hour threshold.",
    evidenceFocus: "Keep IAD arrival proof, airline messages, boarding pass and pre-clearance context.",
    faqQuestion: "Is the purpose of travel relevant?",
    faqAnswer: "Usually no for fixed compensation. The purpose may explain urgency, but EU261 amounts are set by law.",
  },
  "dublin-pittsburgh-delayed-eu261-2026": {
    scenario: "A new route can create confusion because passengers may not know which disruption data or alternatives are available yet.",
    decisionPoint: "Treat a new route like any other long-haul covered departure: distance, delay, cause and operating carrier decide.",
    evidenceFocus: "Keep launch-route communications, schedule-change notices, boarding pass and final arrival proof.",
    faqQuestion: "Does a new route change EU261 rights?",
    faqAnswer: "No. Newness may affect rerouting options, but the core EU261 compensation test remains the same.",
  },
  "dublin-cancun-delayed-aer-lingus-eu261": {
    scenario: "Dublin-Cancun leisure passengers may be focused on holiday disruption, but the legal claim starts with long-haul EU261 coverage.",
    decisionPoint: "Check whether the flight departed Ireland and whether final arrival delay reached the threshold.",
    evidenceFocus: "Keep package documents, hotel transfer timing, Aer Lingus notices and Cancun arrival evidence.",
    faqQuestion: "Does a holiday package change the airline claim?",
    faqAnswer: "Usually the EU261 claim remains against the operating carrier. Package documents can still help prove timing and losses.",
  },
  "shannon-new-york-delayed-eu261-600": {
    scenario: "Shannon-New York is a focused long-haul case where US pre-clearance and EUR600 compensation often overlap.",
    decisionPoint: "Confirm whether the disrupted leg departed Shannon or the United States and whether the operating carrier changes the return analysis.",
    evidenceFocus: "Keep SNN pre-clearance context, boarding pass, New York arrival proof and airline reason.",
    faqQuestion: "Does Shannon pre-clearance reduce EU261 rights?",
    faqAnswer: "No. Pre-clearance does not change the Irish departure point for EU261 analysis.",
  },
  "return-flight-usa-ireland-eu261-applies": {
    scenario: "The return from the US is the trap: Aer Lingus may be covered, while American, United or Delta often are not under EU261.",
    decisionPoint: "Identify the operating carrier before assuming the same rights as the Dublin outbound.",
    evidenceFocus: "Keep the return boarding pass, carrier name, US departure airport, delay reason and arrival proof in Ireland.",
    faqQuestion: "Why does the US return depend on airline?",
    faqAnswer: "EU261 can cover arrivals into the EU on EU carriers, but non-EU carriers departing outside Europe are usually outside EU261.",
  },
  "non-eu-airlines-dublin-usa-eu261": {
    scenario: "American, United and Delta can all be covered from Dublin, but the same brands often fall outside EU261 from the US.",
    decisionPoint: "Use a two-column approach: Dublin-to-USA and USA-to-Ireland, then apply carrier rules to each direction.",
    evidenceFocus: "Keep each leg's operating carrier, departure airport, arrival delay and airline explanation separately.",
    faqQuestion: "Are US airlines covered when leaving Dublin?",
    faqAnswer: "Yes, Irish departures can be covered regardless of airline nationality. The US-origin return is usually the harder leg.",
  },
  "long-haul-delayed-ireland-600-rights": {
    scenario: "Irish long-haul passengers often have the highest-value claims, especially when several family members travel on one booking.",
    decisionPoint: "Do not estimate by ticket price; check the long-haul distance band and final arrival delay.",
    evidenceFocus: "Keep all passenger names, booking reference, boarding passes, delay messages and final arrival proof.",
    faqQuestion: "Can each passenger receive EUR600?",
    faqAnswer: "Yes, if each passenger had a confirmed booking and the covered long-haul flight qualifies.",
  },
  "dublin-london-delayed-eu261-compensation": {
    scenario: "Dublin-London is frequent, short and direction-sensitive because London departures now usually sit under UK261.",
    decisionPoint: "From Dublin use EU261; from London use UK261, then check final arrival delay.",
    evidenceFocus: "Keep separate evidence for each direction, especially if the trip was a same-day return.",
    faqQuestion: "Is Dublin-London always EU261?",
    faqAnswer: "No. Dublin departures are generally EU261, while London departures are generally UK261 after Brexit.",
  },
  "dublin-amsterdam-delayed-klm-ryanair": {
    scenario: "Dublin-Amsterdam can be a point-to-point Ryanair trip or a KLM hub connection, and those are different risk profiles.",
    decisionPoint: "Check whether Amsterdam was the final stop or a protected connection to another destination.",
    evidenceFocus: "Keep the full itinerary, carrier name, Amsterdam arrival time and any missed onward boarding pass.",
    faqQuestion: "Why does Amsterdam hub status matter?",
    faqAnswer: "If Amsterdam was a connection on one booking, final-destination delay can matter more than the Amsterdam arrival alone.",
  },
  "dublin-paris-delayed-aer-lingus-ryanair": {
    scenario: "Dublin-Paris claims can involve business trips, weekend travel or onward CDG connections.",
    decisionPoint: "Confirm whether Paris was the final destination or a connection point before measuring the delay.",
    evidenceFocus: "Keep carrier messages, Paris arrival proof and any onward connection documents.",
    faqQuestion: "Does the airline choice change the Dublin-Paris claim?",
    faqAnswer: "It can affect evidence and handling, but both Irish/EU departures and EU carriers are generally strong under EU261.",
  },
  "dublin-barcelona-delayed-ryanair-vueling": {
    scenario: "Dublin-Barcelona holiday delays often create care costs, but fixed compensation still follows distance and arrival delay.",
    decisionPoint: "Check whether the delay reached the threshold at Barcelona and whether the airline proves a valid defence.",
    evidenceFocus: "Keep boarding pass, Barcelona arrival proof, airline app messages and receipts for meals or transport.",
    faqQuestion: "Can holiday costs increase compensation?",
    faqAnswer: "No. Fixed EU261 compensation is statutory, but receipts may support separate care or reimbursement claims.",
  },
  "dublin-lanzarote-delayed-ryanair-eu261": {
    scenario: "The Canary Islands are often misunderstood because they are geographically off Africa but legally relevant to EU travel rights.",
    decisionPoint: "Do not treat Lanzarote like a non-EU return; EU261 can be strong in both directions when the route is covered.",
    evidenceFocus: "Keep outbound and return documents, Ryanair notices and proof of final arrival in Dublin or Lanzarote.",
    faqQuestion: "Does EU261 apply to the Canary Islands?",
    faqAnswer: "Yes, the Canary Islands are treated within the EU261 travel-rights context, so covered routes can qualify.",
  },
  "dublin-tenerife-delayed-ryanair-aer-lingus": {
    scenario: "Dublin-Tenerife passengers often face peak-season congestion, but airlines still need a valid reason to avoid compensation.",
    decisionPoint: "Separate airport congestion or weather claims from airline-controlled operational delays.",
    evidenceFocus: "Keep Tenerife arrival proof, airline reason, weather context if relevant and receipts from the wait.",
    faqQuestion: "Is Tenerife treated as outside EU261?",
    faqAnswer: "No. Tenerife is in the Canary Islands, and EU261 can apply to covered Dublin-Tenerife travel.",
  },
  "dublin-faro-algarve-delayed-ryanair-eu261": {
    scenario: "Dublin-Faro is a classic leisure route where passengers may have hotel, car-hire or villa check-in timing evidence.",
    decisionPoint: "Use arrival delay and airline cause, not the value of the holiday, to decide fixed compensation.",
    evidenceFocus: "Keep Faro arrival proof, Ryanair messages and any care receipts from Dublin or Faro.",
    faqQuestion: "Does car-hire disruption change the EU261 amount?",
    faqAnswer: "No. It can help document timing, but EU261 fixed compensation remains based on eligibility and distance.",
  },
  "dublin-malaga-delayed-ryanair-aer-lingus": {
    scenario: "Dublin-Malaga delays often affect families and groups, so each passenger's booking status matters.",
    decisionPoint: "Check whether every passenger had a confirmed booking and reached Malaga late enough.",
    evidenceFocus: "Keep the group booking confirmation, all boarding passes, airline notices and final arrival proof.",
    faqQuestion: "Can a family claim per passenger?",
    faqAnswer: "Yes, each qualifying passenger can usually claim individually if the covered flight meets the EU261 threshold.",
  },
  "dublin-lisbon-delayed-tap-ryanair-eu261": {
    scenario: "Dublin-Lisbon can involve TAP connections onward to Madeira, Brazil or other destinations.",
    decisionPoint: "If Lisbon was a hub stop on one booking, measure the delay at the final destination.",
    evidenceFocus: "Keep TAP or Ryanair documents, connection details, rebooking messages and final arrival proof.",
    faqQuestion: "Does an onward TAP connection matter?",
    faqAnswer: "Yes, if it was on one booking. Final destination delay can control the compensation question.",
  },
  "dublin-rome-delayed-ryanair-aer-lingus": {
    scenario: "Dublin-Rome passengers may fly for city breaks, cruises or onward Italy connections.",
    decisionPoint: "Confirm the actual arrival time in Rome or the protected final destination before estimating compensation.",
    evidenceFocus: "Keep Rome arrival proof, airline notices and any connection or cruise timing documents.",
    faqQuestion: "Is Rome distance usually EUR250 or EUR400?",
    faqAnswer: "The route distance can place many Dublin-Rome claims in the medium band, but eligibility and exact distance assessment still matter.",
  },
  "dublin-milan-delayed-ryanair-eu261": {
    scenario: "Dublin-Milan may involve different Milan-area airports, which can complicate rerouting and arrival evidence.",
    decisionPoint: "Check the booked airport and any rerouted airport before assessing final arrival and care costs.",
    evidenceFocus: "Keep the booked airport code, replacement airport details, transfer receipts and final arrival proof.",
    faqQuestion: "Does rerouting to another Milan airport matter?",
    faqAnswer: "It can matter for arrival timing and transport costs. Keep the reroute details and receipts.",
  },
  "dublin-warsaw-delayed-lot-ryanair-eu261": {
    scenario: "Dublin-Warsaw serves both Irish travellers and Poland's large community in Ireland, with LOT and Ryanair creating different connection patterns.",
    decisionPoint: "Check whether Warsaw was the final destination or a LOT connection onward on one booking.",
    evidenceFocus: "Keep Dublin-Warsaw boarding pass, onward LOT itinerary if any, missed-connection proof and final arrival evidence.",
    faqQuestion: "Why does LOT vs Ryanair matter on Dublin-Warsaw?",
    faqAnswer: "LOT may involve protected hub connections through Warsaw, while Ryanair is often point-to-point. That changes missed-connection analysis.",
  },
  "dublin-oslo-delayed-aer-lingus-2026": {
    scenario: "A newer Dublin-Oslo service may leave passengers unsure about alternatives if a flight is disrupted.",
    decisionPoint: "New route or not, EU261 still asks about coverage, final arrival delay and the airline's reason.",
    evidenceFocus: "Keep schedule-change notices, Aer Lingus communications, boarding pass and Oslo arrival proof.",
    faqQuestion: "Does a new route reduce passenger rights?",
    faqAnswer: "No. Route novelty can affect practical rerouting, but it does not remove EU261 rights.",
  },
  "cork-london-delayed-aer-lingus-ryanair": {
    scenario: "Cork-London is direction-sensitive like Dublin-London, but Cork passengers may have fewer same-day alternatives.",
    decisionPoint: "From Cork, EU261 is usually the start; from London, UK261 is usually the start.",
    evidenceFocus: "Keep Cork or London departure proof, airline messages, replacement options and final arrival evidence.",
    faqQuestion: "Is Cork-London treated like Dublin-London?",
    faqAnswer: "Legally it has the same EU261 versus UK261 direction issue, though practical rerouting options may differ.",
  },
  "cork-nice-delayed-aer-lingus-2026": {
    scenario: "Cork-Nice leisure passengers may face seasonal schedules where next available flights are limited.",
    decisionPoint: "If a delay or cancellation occurs, check compensation and care rights separately from holiday disruption.",
    evidenceFocus: "Keep Aer Lingus schedule notices, boarding pass, Nice arrival proof and accommodation or transfer receipts.",
    faqQuestion: "Does a seasonal route have weaker rights?",
    faqAnswer: "No. Seasonal operation does not remove EU261 rights when the flight is covered.",
  },
  "cork-prague-delayed-aer-lingus-2026": {
    scenario: "Cork-Prague becoming year-round makes it useful for both leisure and regular travel, but the same EU261 test applies.",
    decisionPoint: "Use the actual arrival delay and airline reason, not the route's seasonal history, to assess the claim.",
    evidenceFocus: "Keep Cork departure proof, Prague arrival time, Aer Lingus notices and any rerouting details.",
    faqQuestion: "Does year-round service change compensation?",
    faqAnswer: "No. It may improve practical rerouting options, but compensation still follows EU261 eligibility.",
  },
  "dublin-dubai-delayed-emirates-eu261": {
    scenario: "Dublin-Dubai on Emirates is one of the clearest examples of EU261 applying outbound but usually not on the non-EU return.",
    decisionPoint: "Analyse the Dublin departure and Dubai departure as separate legal events.",
    evidenceFocus: "Keep Emirates notices, Dubai arrival or Dublin return evidence and the operating carrier for each leg.",
    faqQuestion: "Does Emirates owe EU261 from Dubai to Dublin?",
    faqAnswer: "Usually no, because Emirates is not an EU carrier and the flight departs outside Europe. Dublin-Dubai is different.",
  },
  "dublin-istanbul-delayed-turkish-eu261": {
    scenario: "Dublin-Istanbul can be either a final destination or a major connection point into Asia and beyond.",
    decisionPoint: "If the itinerary continues beyond Istanbul on one booking, final destination arrival may be decisive.",
    evidenceFocus: "Keep Turkish Airlines itinerary, Istanbul connection details, replacement flights and final arrival proof.",
    faqQuestion: "Does Istanbul being outside the EU block Dublin departure claims?",
    faqAnswer: "No. A Dublin departure can still be covered. The return from Istanbul on Turkish is usually the harder EU261 case.",
  },
  "lot-polish-airlines-delay-dublin-eu261": {
    scenario: "LOT from Dublin matters for both Irish passengers and Poland's community in Ireland, especially on Warsaw hub connections.",
    decisionPoint: "Check whether the delay ended in Warsaw or caused a missed onward flight on the same LOT booking.",
    evidenceFocus: "Keep LOT itinerary, Warsaw connection proof, boarding passes and final arrival evidence.",
    faqQuestion: "Does LOT being Polish help EU261 coverage?",
    faqAnswer: "Yes. LOT is an EU carrier, which strengthens coverage on many routes involving Ireland and Warsaw.",
  },
  "lot-dublin-warsaw-delayed-compensation": {
    scenario: "Dublin-Warsaw is often a shorter compensation-band claim, but repeated commuter or family travel makes evidence easy to find.",
    decisionPoint: "Check the route distance band and final arrival delay before assuming the amount.",
    evidenceFocus: "Keep Dublin and Warsaw boarding proof, LOT or Ryanair messages and actual arrival evidence.",
    faqQuestion: "Is Dublin-Warsaw usually a EUR250 case?",
    faqAnswer: "Often the short-distance band is relevant, but the exact amount should still be checked against distance and eligibility.",
  },
  "lot-cancelled-flight-ireland-rights": {
    scenario: "A LOT cancellation from Ireland can affect onward Warsaw connections and family travel plans.",
    decisionPoint: "Look at cancellation notice, rerouting arrival and whether an onward leg was protected on one booking.",
    evidenceFocus: "Keep the cancellation notice, LOT rerouting options, onward itinerary and final arrival proof.",
    faqQuestion: "Can a LOT cancellation from Ireland create compensation?",
    faqAnswer: "Yes, if the cancellation timing, reason and rerouting outcome meet EU261 conditions.",
  },
  "lot-rejected-compensation-ireland-force": {
    scenario: "A LOT rejection may be easier to challenge when the Warsaw hub timeline and final arrival are clearly documented.",
    decisionPoint: "Ask whether LOT proved the specific defence and whether the final destination delay was properly considered.",
    evidenceFocus: "Keep LOT's refusal, original claim, connection documents and final arrival records.",
    faqQuestion: "What is the strongest reply to a LOT refusal?",
    faqAnswer: "A clear timeline with booking, delay, missed connection if any, final arrival and a request for the specific operational reason.",
  },
  "lot-missed-connection-warsaw-eu261": {
    scenario: "A Dublin-Warsaw delay can become a much larger issue if it breaks a protected onward connection.",
    decisionPoint: "Single booking is the key; separate tickets are much weaker for missed-connection compensation.",
    evidenceFocus: "Keep the full LOT itinerary, missed boarding proof, rebooking documents and final arrival time.",
    faqQuestion: "Does Warsaw missed connection compensation depend on one booking?",
    faqAnswer: "Yes. The claim is strongest when Dublin-Warsaw and the onward leg were sold as one itinerary.",
  },
  "lot-dublin-new-york-warsaw-600-delayed": {
    scenario: "Dublin-Warsaw-New York can put a transatlantic EUR600 band into play if the Warsaw connection is missed on one booking.",
    decisionPoint: "Measure the delay at New York, not merely the delay on the Dublin-Warsaw sector.",
    evidenceFocus: "Keep the full DUB-WAW-JFK itinerary, missed-connection proof, new boarding passes and New York arrival evidence.",
    faqQuestion: "Can a European first leg lead to EUR600?",
    faqAnswer: "Yes, if the single booking was to New York and the covered disruption caused a qualifying final arrival delay.",
  },
  "overbooking-ireland-denied-boarding-600": {
    scenario: "Overbooking cases can move quickly at the gate, and passengers may be pressured to volunteer without understanding the consequences.",
    decisionPoint: "Distinguish voluntary surrender of the seat from involuntary denied boarding.",
    evidenceFocus: "Keep gate notices, written denied-boarding confirmation, volunteer offer terms and replacement flight details.",
    faqQuestion: "Is volunteering the same as denied boarding?",
    faqAnswer: "No. Volunteers usually accept negotiated benefits, while involuntary denied boarding can trigger fixed EU261 compensation.",
  },
  "downgrade-ireland-business-economy-refund": {
    scenario: "A business-class passenger moved to economy may have a separate downgrade refund even without a classic delay claim.",
    decisionPoint: "Check the cabin actually flown, route length and ticket segment affected by the downgrade.",
    evidenceFocus: "Keep the original fare class, boarding pass showing cabin, seat assignment, airline explanation and ticket price breakdown.",
    faqQuestion: "Is downgrade compensation the same as delay compensation?",
    faqAnswer: "No. Downgrade rights are a separate EU261 concept and can apply even when the flight arrives on time.",
  },
  "charter-flight-delayed-ireland-eu261": {
    scenario: "Holiday charter passengers often assume the package organiser is the only point of contact, but EU261 usually targets the operating carrier.",
    decisionPoint: "Identify the operating airline, not just the tour operator or holiday brand.",
    evidenceFocus: "Keep package documents, flight number, operating carrier name, airport notices and final arrival proof.",
    faqQuestion: "Do charter flights from Ireland have EU261 rights?",
    faqAnswer: "They can. EU261 can apply to charter and holiday flights when the route and disruption qualify.",
  },
  "ota-ticket-skyscanner-booking-claim-ireland": {
    scenario: "Tickets found through Skyscanner or bought through Booking.com, Expedia or Travel Republic can create confusion about who owes compensation.",
    decisionPoint: "The EU261 compensation claim is normally against the operating air carrier, not the search or booking platform.",
    evidenceFocus: "Keep both the OTA confirmation and the airline confirmation, plus any messages showing who operated the flight.",
    faqQuestion: "Does booking through an OTA block EU261?",
    faqAnswer: "Usually no. The operating carrier remains central for compensation, though the OTA may matter for refunds or ticket-service issues.",
  },
  "group-booking-delayed-collective-claim-ireland": {
    scenario: "Families, teams and wedding groups can multiply the value of a valid claim, but each passenger still needs proof of travel.",
    decisionPoint: "Confirm every passenger on the booking had a confirmed seat and suffered the same qualifying disruption.",
    evidenceFocus: "Keep the group booking list, all passenger names, boarding passes and the shared delay or cancellation evidence.",
    faqQuestion: "Can one person claim for a group?",
    faqAnswer: "Often one lead passenger can coordinate, but authority and passenger details should be clear for each individual claim.",
  },
  "airline-bankrupt-eu261-claim-ireland": {
    scenario: "If an airline fails, the legal right may exist but practical recovery can become the hardest part.",
    decisionPoint: "Separate entitlement from collectability; insolvency can change the route and likelihood of payment.",
    evidenceFocus: "Keep claim documents, booking proof, payment method, insolvency notices and any chargeback or insurance correspondence.",
    faqQuestion: "Does airline bankruptcy erase the claim?",
    faqAnswer: "Not automatically, but it can make recovery harder and may require insolvency, card, insurance or package-travel routes.",
  },
  "night-delay-ireland-hotel-meals-transport": {
    scenario: "An overnight delay at Dublin, Cork or Shannon can create immediate hotel and transport needs even before compensation is decided.",
    decisionPoint: "Ask the airline for care first; if you pay yourself, keep receipts and choose reasonable costs.",
    evidenceFocus: "Keep hotel invoice, meal receipts, taxi or bus receipts, airline care refusal and delay messages.",
    faqQuestion: "Are hotel costs separate from EUR600 compensation?",
    faqAnswer: "Yes. Care and reimbursement rights are separate from fixed compensation, although both can arise from the same disruption.",
  },
  "business-travel-delay-employee-employer-ireland": {
    scenario: "An employee delayed on a company-paid ticket may assume the employer owns the EU261 compensation.",
    decisionPoint: "Statutory compensation usually belongs to the passenger, while internal employer policies are a separate matter.",
    evidenceFocus: "Keep the business itinerary, boarding pass, employer booking proof and any travel-policy correspondence if relevant.",
    faqQuestion: "Can the employer take the compensation?",
    faqAnswer: "EU261 compensation is generally a passenger right. Employment policies may affect internal handling, but not the airline's statutory obligation.",
  },
  "miles-ticket-eu261-award-travel-ireland": {
    scenario: "Aer Club, Avios or other award bookings can look 'free', but the passenger still held a confirmed booking.",
    decisionPoint: "Do not let the airline reject the case solely because miles or points were used.",
    evidenceFocus: "Keep the award booking confirmation, taxes and fees receipt, boarding pass and loyalty-account transaction where available.",
    faqQuestion: "Do Avios or Aer Club tickets qualify?",
    faqAnswer: "They can. EU261 generally focuses on confirmed travel, not whether the fare was paid in cash or points.",
  },
  "missed-connection-dublin-one-booking-separate": {
    scenario: "Dublin self-transfer passengers may have two valid tickets but no protected connection between them.",
    decisionPoint: "Single booking versus separate tickets is the core distinction for missed-connection responsibility.",
    evidenceFocus: "Keep booking confirmations showing whether there was one reference or separate references for each leg.",
    faqQuestion: "Why are separate tickets risky?",
    faqAnswer: "Because each airline may only be responsible for its own flight, not for a self-arranged onward connection.",
  },
  "compensation-delayed-flight-ireland-250-400-600": {
    scenario: "Irish passengers need a fast way to estimate amount before checking the harder questions of coverage and cause.",
    decisionPoint: "Use distance for the band, then final arrival delay and airline defence for eligibility.",
    evidenceFocus: "Keep route details, flight number, final arrival proof and the airline's written reason.",
    faqQuestion: "Is the amount based on ticket price?",
    faqAnswer: "No. EU261 amounts are fixed by distance band and eligibility, not by fare paid.",
  },
  "hours-delay-eu261-compensation-ireland": {
    scenario: "A passenger delayed two hours at the gate may receive care rights but still miss the fixed-compensation threshold.",
    decisionPoint: "Use arrival delay at final destination, not departure delay, for the three-hour compensation rule.",
    evidenceFocus: "Keep scheduled and actual arrival times, gate messages and final destination proof.",
    faqQuestion: "Does a two-hour departure delay qualify?",
    faqAnswer: "Usually not for fixed compensation unless final arrival reaches the legal threshold or another qualifying issue applies.",
  },
  "eu261-ryanair-ireland-applies": {
    scenario: "The simplest Ryanair answer is often yes on coverage, but that is only the first step.",
    decisionPoint: "After confirming Ryanair/EU coverage, check final arrival delay and whether Ryanair proves an extraordinary circumstance.",
    evidenceFocus: "Keep Ryanair app screenshots, flight status proof and any refusal wording.",
    faqQuestion: "Is Ryanair always covered in Ireland?",
    faqAnswer: "Ryanair is an EU carrier and Irish departures are covered, but each claim still needs the delay and cause tests.",
  },
  "eu261-aer-lingus-applies": {
    scenario: "Aer Lingus is an EU carrier, which helps both Irish departures and many flights arriving into Ireland.",
    decisionPoint: "The next question is not coverage alone, but whether the disruption meets the delay, cancellation or denied-boarding criteria.",
    evidenceFocus: "Keep Aer Lingus booking details, boarding pass, delay messages and arrival proof.",
    faqQuestion: "Does Aer Lingus being Irish make claims automatic?",
    faqAnswer: "No. It strengthens coverage, but compensation still depends on the disruption threshold and the airline's defence.",
  },
  "eu261-american-airlines-dublin": {
    scenario: "American Airlines from Dublin is a common misconception: non-EU airline, but EU airport departure.",
    decisionPoint: "Dublin departure can be covered; US departure on American usually is not under EU261.",
    evidenceFocus: "Keep direction-specific documents, especially Dublin departure proof and US return carrier evidence.",
    faqQuestion: "What is the one-line rule for American Airlines?",
    faqAnswer: "From Dublin, EU261 can apply. From the United States on American Airlines, EU261 usually does not.",
  },
  "extraordinary-circumstances-eu261-ireland": {
    scenario: "Irish passengers often see the phrase 'extraordinary circumstances' before seeing any evidence.",
    decisionPoint: "A label is not proof; the airline should connect the event to the specific flight and show reasonable measures.",
    evidenceFocus: "Keep the airline's exact wording, weather or ATC context, and any timeline that contradicts the refusal.",
    faqQuestion: "Who must prove extraordinary circumstances?",
    faqAnswer: "The airline must prove the defence. Passengers should preserve evidence and challenge vague explanations.",
  },
  "how-long-claim-eu261-ireland": {
    scenario: "Ireland's six-year window can turn old inbox searches into valuable claims.",
    decisionPoint: "Check the date of the flight before assuming the claim is stale.",
    evidenceFocus: "Search email, calendars, bank statements, loyalty accounts and passport stamps for old flight proof.",
    faqQuestion: "Why is Ireland's period a conversion advantage?",
    faqAnswer: "Because many passengers who would be out of time elsewhere may still be able to check older Irish claims.",
  },
  "ryanair-wont-pay-claim-ireland": {
    scenario: "When Ryanair will not pay, the case becomes a documentation and escalation exercise rather than a new complaint from scratch.",
    decisionPoint: "Identify whether Ryanair disputes coverage, delay length, cause or passenger evidence.",
    evidenceFocus: "Keep the claim, refusal, follow-up requests, flight evidence and any IAA or court-ready summary.",
    faqQuestion: "What should I not do after a Ryanair refusal?",
    faqAnswer: "Do not restart with vague messages. Build a precise timeline and ask for the specific reason behind the refusal.",
  },
  "eu261-claim-3-years-ago-ireland": {
    scenario: "A three-year-old Irish disruption is not automatically too old, which is a major difference from many passenger assumptions.",
    decisionPoint: "Check limitation and evidence availability before abandoning the claim.",
    evidenceFocus: "Recover old booking emails, boarding passes, bank payments, airline app history and travel-calendar entries.",
    faqQuestion: "Is three years too late in Ireland?",
    faqAnswer: "Often no. Ireland's limitation period can allow many older EU261 claims, though evidence becomes more important.",
  },
  "voucher-instead-cash-ryanair-ireland": {
    scenario: "A Ryanair voucher can look like a quick solution but may be less useful than cash compensation.",
    decisionPoint: "Read whether the voucher is optional, whether accepting it waives rights and whether cash was requested.",
    evidenceFocus: "Keep screenshots of the offer, terms, expiry date and your request for cash.",
    faqQuestion: "What if I already clicked accept?",
    faqAnswer: "The answer depends on the wording and circumstances. Save the acceptance terms and get the case reviewed before assuming it is over.",
  },
  "eu261-return-flight-usa-ireland": {
    scenario: "Return flights from the USA are where many Irish passengers lose the EU261 protection they had on the outbound.",
    decisionPoint: "Ask whether the operating carrier is EU-based; Aer Lingus is very different from American, United or Delta.",
    evidenceFocus: "Keep the US departure airport, operating carrier, boarding pass and arrival time in Ireland.",
    faqQuestion: "Can Aer Lingus be covered from the USA?",
    faqAnswer: "Yes, Aer Lingus as an EU carrier can make EU261 relevant on the return, unlike many US carriers.",
  },
  "iaa-complain-airline-ireland": {
    scenario: "The IAA is most useful when the airline has already had a chance to answer and the passenger can show a structured record.",
    decisionPoint: "Escalate with a concise timeline rather than a long emotional narrative.",
    evidenceFocus: "Attach booking, boarding pass, airline claim, airline reply, flight status and a short explanation of what is disputed.",
    faqQuestion: "What makes an IAA complaint stronger?",
    faqAnswer: "A clear chronology and complete documents make it easier to assess whether the airline respected passenger rights.",
  },
  "eu261-compensation-payout-time-ireland": {
    scenario: "Some claims pay quickly, but airline silence, vague refusals or missing evidence can stretch the timeline.",
    decisionPoint: "After a reasonable response period, decide whether to escalate, correct missing evidence or use a claim service.",
    evidenceFocus: "Keep all dates: claim sent, airline acknowledgement, requests for documents, refusal and payment promises.",
    faqQuestion: "Why do payouts take longer?",
    faqAnswer: "Delays usually come from disputed cause, missing documents, airline backlogs or escalation. A clean evidence pack helps.",
  },
  "eu261-charter-flights-ireland": {
    scenario: "Charter passengers may have a tour operator, airline and travel agent in the same booking chain.",
    decisionPoint: "For EU261 compensation, identify the operating air carrier and the airport of departure.",
    evidenceFocus: "Keep the package invoice, flight number, operating airline name, delay proof and final arrival time.",
    faqQuestion: "Is the tour operator responsible for EU261?",
    faqAnswer: "The operating carrier is usually central for EU261 compensation, though package organisers may matter for other remedies.",
  },
  "eu261-travel-agent-ireland-claim": {
    scenario: "A travel-agent booking can make passengers chase the wrong party for compensation.",
    decisionPoint: "Use the travel agent for ticket-service issues, but direct EU261 compensation analysis at the operating carrier.",
    evidenceFocus: "Keep agent confirmation, airline confirmation, ticket number, flight number and carrier communications.",
    faqQuestion: "Can the airline reject me because I used an agent?",
    faqAnswer: "Usually no. Booking channel alone should not remove EU261 rights against the operating carrier.",
  },
  "aer-lingus-hotel-overnight-delay-ireland": {
    scenario: "An overnight Aer Lingus delay can require immediate hotel decisions while passengers are tired and information is limited.",
    decisionPoint: "Ask Aer Lingus for care, but if you must pay, keep costs reasonable and documented.",
    evidenceFocus: "Keep hotel, meal and transport receipts, Aer Lingus care messages and proof of overnight delay.",
    faqQuestion: "Are hotel rights separate from compensation?",
    faqAnswer: "Yes. Care rights can apply during the delay even while the fixed compensation issue is still disputed.",
  },
  "ryanair-cancelled-14-days-before-ireland": {
    scenario: "A Ryanair cancellation less than 14 days before departure deserves a close look even if a refund or reroute was offered.",
    decisionPoint: "Check notice time, reason and how late any replacement flight arrived compared with the original schedule.",
    evidenceFocus: "Keep the cancellation timestamp, original schedule, replacement itinerary and Ryanair's stated reason.",
    faqQuestion: "Does the 14-day rule guarantee compensation?",
    faqAnswer: "No. It makes the case worth checking, but rerouting timing and extraordinary circumstances can still affect the result.",
  },
  "sue-airline-irish-courts-eu261": {
    scenario: "Some Irish passengers need a court route when airline correspondence and enforcement routes do not resolve the dispute.",
    decisionPoint: "Match the claim value and facts to the right route; Small Claims is not suitable for every airline dispute.",
    evidenceFocus: "Prepare a court-ready bundle with timeline, claim, refusal, documents, legal basis and amount claimed.",
    faqQuestion: "Is court always the best next step?",
    faqAnswer: "No. It can be useful, but many passengers prefer specialist handling or escalation before starting formal proceedings.",
  },
  "claimwinger-airhelp-flightright-ireland": {
    scenario: "Irish passengers comparing claim companies should look beyond brand awareness to fee model, legal route and Ireland-specific understanding.",
    decisionPoint: "Compare risk, percentage fee, communication, escalation ability and knowledge of IAA, UK261 and Ireland's limitation period.",
    evidenceFocus: "Prepare the same evidence pack before comparing providers so each can assess the identical case.",
    faqQuestion: "What matters most when comparing claim companies?",
    faqAnswer: "The best choice depends on fee, risk, transparency and ability to handle the exact Irish route and airline issue.",
  },
  "claim-company-vs-diy-ireland-eu261": {
    scenario: "A simple claim can be DIY, but a rejected, old, transatlantic or non-EU carrier case may need more pressure.",
    decisionPoint: "Choose DIY when facts are simple and documents are strong; use help when refusal, limitation or legal complexity appears.",
    evidenceFocus: "Keep a complete pack either way: booking, boarding pass, delay proof, airline reason and correspondence.",
    faqQuestion: "Is no-win, no-fee worth it?",
    faqAnswer: "It can be when the case is complex or the airline resists. DIY may suit straightforward claims where the passenger is comfortable managing escalation.",
  },
  "eu261-6-years-ireland-limitation-period": {
    scenario: "Ireland's six-year period is one of the strongest reasons to audit old inboxes for delayed or cancelled flights.",
    decisionPoint: "The older the flight, the more important it is to reconstruct documents before contacting the airline.",
    evidenceFocus: "Search email archives, bank statements, loyalty accounts, calendar events, passport stamps and old app notifications.",
    faqQuestion: "Can I claim flights from 2020 in Ireland?",
    faqAnswer: "Potentially yes, depending on dates, facts and evidence. Ireland's six-year period makes older claims worth checking.",
  },
  "small-claims-court-airline-ireland": {
    scenario: "Small Claims can be a practical Irish route for some airline disputes, but it works best with a precise and documented case.",
    decisionPoint: "Check claim value, suitability and whether the dispute fits the procedure before filing.",
    evidenceFocus: "Prepare booking proof, claim correspondence, airline refusal, timeline, amount calculation and supporting receipts.",
    faqQuestion: "What makes a Small Claims filing credible?",
    faqAnswer: "A concise chronology, correct defendant, clear legal basis and complete documents are more persuasive than a broad complaint.",
  },
};

export function getEnIrelandArticleProfile(
  article: BlogArticleEnIreland,
): EnIrelandArticleEditorialProfile {
  return enIrelandArticleProfiles[article.slug] || defaultProfile;
}
